// Copyright 2026 The Walk Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"
)

// outputPrefix starts the names of all generated files.
const outputPrefix = "zwinmd_"

type generator struct {
	m    *metadata
	s    *spec
	pkg  *goPackage
	errs []string
}

func (g *generator) errorf(line int, format string, args ...any) {
	g.errs = append(g.errs, fmt.Sprintf("line %d: %s", line, fmt.Sprintf(format, args...)))
}

func header(b *bytes.Buffer, s *spec, imports ...string) {
	fmt.Fprintf(b, "// Code generated by winmdgen from %s %s; DO NOT EDIT.\n\n", nugetPackage, s.metaVersion)
	b.WriteString("//go:build windows\n\npackage win\n\n")
	if len(imports) > 0 {
		b.WriteString("import (\n")
		std := true
		for _, imp := range imports {
			if std && strings.Contains(imp, ".") {
				b.WriteString("\n")
				std = false
			}
			fmt.Fprintf(b, "\t%q\n", imp)
		}
		b.WriteString(")\n\n")
	}
}

// constants generates the const declarations.
func (g *generator) constants() []byte {
	type entry struct {
		name, decl string
	}
	groups := make(map[string][]entry)
	for _, cs := range g.s.constants {
		c, err := g.m.lookupConstant(cs.name)
		if err != nil {
			g.errorf(cs.line, "%v", err)
			continue
		}
		value, err := c.goValue()
		if err != nil {
			g.errorf(cs.line, "%v", err)
			continue
		}
		decl := cs.name
		if cs.goType != "" {
			decl += " " + cs.goType
		}
		decl += " = " + value
		group := c.enum
		if group == "" {
			group = c.namespace
		}
		groups[group] = append(groups[group], entry{cs.name, decl})
	}

	var b bytes.Buffer
	header(&b, g.s)
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		entries := groups[k]
		sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })
		fmt.Fprintf(&b, "// %s\nconst (\n", k)
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%s\n", e.decl)
		}
		b.WriteString(")\n\n")
	}
	return b.Bytes()
}

func (m *metadata) lookupConstant(name string) (*constant, error) {
	cs := m.constants[name]
	if len(cs) == 0 {
		return nil, fmt.Errorf("constant %s not found in the metadata", name)
	}
	c := cs[0]
	for _, c2 := range cs[1:] {
		if c2.kind != c.kind || c2.ival != c.ival || c2.uval != c.uval || c2.fval != c.fval || c2.sval != c.sval {
			return nil, fmt.Errorf("constant %s has different values in %s and %s", name, c.namespace, c2.namespace)
		}
	}
	if c.arch != archAll {
		return nil, fmt.Errorf("constant %s is specific to %v", name, c.arch)
	}
	return c, nil
}

// goValue returns the value of a constant as a Go literal.
func (c *constant) goValue() (string, error) {
	if c.guid != nil {
		return "", fmt.Errorf("constant %s is a GUID", c.name)
	}
	if i, u, signed, ok := c.integer(); ok {
		switch {
		case signed && i < 0:
			return strconv.FormatInt(i, 10), nil
		case signed:
			u = uint64(i)
		}
		if u < 10 {
			return strconv.FormatUint(u, 10), nil
		}
		return "0x" + strconv.FormatUint(u, 16), nil
	}
	switch c.kind {
	case 0x0c, 0x0d: // R4, R8
		return strconv.FormatFloat(c.fval, 'g', -1, 64), nil
	case 0x0e: // STRING
		return strconv.Quote(c.sval), nil
	}
	return "", fmt.Errorf("constant %s has unsupported type %v", c.name, c.kind)
}

// genFunc is a function ready to be written.
type genFunc struct {
	spec    *funcSpec
	method  *method // on the first architecture
	proc    string  // name of the LazyProc variable
	params  []param // with Go types and code shapes resolved
	shapes  []shape
	byValue []int // size of a struct passed by value, 0 for other parameters
	result  string
	rshape  shape

	// methods holds the method of each architecture if the function
	// uses a fallback on some of them, nil otherwise.
	methods map[arch]*method
}

// functions generates the DLL and procedure variables and the wrapper
// functions. The procedure variables of functions with a fallback differ
// between architectures and are returned separately for each.
func (g *generator) functions() (common []byte, perArch map[arch][]byte) {
	dlls := make(map[string]*dllSpec)
	for _, d := range g.s.dlls {
		dlls[d.name] = d
	}

	var funcs []*genFunc
	for _, fs := range g.s.functions {
		f, err := g.function(fs)
		if err != nil {
			g.errorf(fs.line, "%s: %v", fs.name, err)
			continue
		}
		if dlls[f.method.dll] == nil {
			g.errorf(fs.line, "%s: no dll directive for %s", fs.name, f.method.dll)
			continue
		}
		funcs = append(funcs, f)
	}
	sort.Slice(funcs, func(i, j int) bool { return funcs[i].spec.name < funcs[j].spec.name })

	var body bytes.Buffer
	for _, f := range funcs {
		g.writeFunc(&body, f)
	}

	var b bytes.Buffer
	imports := []string{"syscall"}
	if bytes.Contains(body.Bytes(), []byte("unsafe.")) {
		imports = append(imports, "unsafe")
	}
	header(&b, g.s, append(imports, "golang.org/x/sys/windows")...)
	b.WriteString("var (\n")
	// The DLL variables are also used by hand-written code.
	for _, d := range g.s.dlls {
		fmt.Fprintf(&b, "\t%s = windows.NewLazySystemDLL(%q)\n", d.goName, d.name)
	}
	b.WriteString("\n")
	for _, f := range funcs {
		if f.methods == nil {
			fmt.Fprintf(&b, "\t%s = %s.NewProc(%q)\n", f.proc, dlls[f.method.dll].goName, f.method.entry)
		}
	}
	b.WriteString(")\n\n")
	b.Write(body.Bytes())

	perArch = make(map[arch][]byte)
	for _, an := range archNames {
		var vars bytes.Buffer
		for _, f := range funcs {
			if md := f.methods[an.arch]; md != nil {
				fmt.Fprintf(&vars, "\t%s = %s.NewProc(%q)\n", f.proc, dlls[md.dll].goName, md.entry)
			}
		}
		if vars.Len() == 0 {
			continue
		}
		var ab bytes.Buffer
		header(&ab, g.s)
		ab.WriteString("var (\n")
		ab.Write(vars.Bytes())
		ab.WriteString(")\n")
		perArch[an.arch] = ab.Bytes()
	}
	return b.Bytes(), perArch
}

// goSignature returns the Go parameter and result types.
func (f *genFunc) goSignature() string {
	var types []string
	for _, p := range f.params {
		types = append(types, p.typ.name)
	}
	return "(" + strings.Join(types, ", ") + ") " + f.result
}

// lookupMethod finds the metadata function NAME+"W", or NAME if there is
// no such function.
func (m *metadata) lookupMethod(name string, exact bool) (*method, error) {
	mds := m.methods[name]
	if !exact {
		if mds = m.methods[name+"W"]; len(mds) == 0 {
			mds = m.methods[name]
		}
	}
	switch {
	case len(mds) == 0:
		return nil, fmt.Errorf("function not found in the metadata")
	case len(mds) > 1:
		return nil, fmt.Errorf("function has %d definitions in the metadata", len(mds))
	}
	if mds[0].dll == "" {
		return nil, fmt.Errorf("function has no DLL import")
	}
	return mds[0], nil
}

func (g *generator) function(fs *funcSpec) (*genFunc, error) {
	name, exact := fs.name, false
	if fs.entry != "" {
		name, exact = fs.entry, true
	}
	md, err := g.m.lookupMethod(name, exact)
	if err != nil {
		return nil, err
	}
	// methods[a] is the method used on architecture a.
	methods := make(map[arch]*method)
	for _, an := range archNames {
		methods[an.arch] = md
	}
	switch {
	case md.arch != archAll && fs.fallback == "":
		return nil, fmt.Errorf("function is specific to %v", md.arch)
	case md.arch == archAll && fs.fallback != "":
		return nil, fmt.Errorf("function exists on all architectures, fallback is not used")
	case fs.fallback != "":
		fb, err := g.m.lookupMethod(fs.fallback, false)
		if err != nil {
			return nil, fmt.Errorf("fallback %s: %w", fs.fallback, err)
		}
		if fb.arch|md.arch != archAll {
			return nil, fmt.Errorf("fallback %s does not exist on %v", fs.fallback, archAll&^md.arch)
		}
		if fb.dll != md.dll {
			return nil, fmt.Errorf("fallback %s is in %s, not in %s", fs.fallback, fb.dll, md.dll)
		}
		for _, an := range archNames {
			if md.arch&an.arch == 0 {
				methods[an.arch] = fb
			}
		}
	}

	// The Go signature must be the same on all architectures.
	var f *genFunc
	for _, an := range archNames {
		amd := methods[an.arch]
		tm := &typeMapper{m: g.m, arch: an.arch, pkg: g.pkg, rawBool: fs.rawBool}
		sig, err := tm.signature(amd)
		if err != nil {
			return nil, err
		}
		af, err := g.project(fs, amd, sig, an.arch)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", an.name, err)
		}
		if f == nil {
			f = af
			continue
		}
		if af.goSignature() != f.goSignature() || fmt.Sprint(af.byValue) != fmt.Sprint(f.byValue) {
			return nil, fmt.Errorf("signature differs between architectures")
		}
	}
	f.proc = "proc" + f.method.entry
	if fs.fallback != "" {
		f.methods = methods
		f.proc = "proc" + fs.name
	}
	for name := range fs.params {
		found := false
		for _, p := range f.params {
			found = found || p.name == name
		}
		if !found {
			return nil, fmt.Errorf("no parameter %s", name)
		}
	}
	for i := range f.params {
		f.params[i].name = goParamName(f.params[i].name)
	}
	return f, nil
}

// project applies the overrides of the specification to a metadata
// signature and checks that the result can be passed through
// syscall.SyscallN unchanged.
func (g *generator) project(fs *funcSpec, md *method, sig *signature, a arch) (*genFunc, error) {
	f := &genFunc{spec: fs, method: md}
	for _, p := range sig.params {
		switch {
		case p.typ.kind == kindFloat:
			return nil, fmt.Errorf("parameter %s is a floating-point value", p.name)
		case p.typ.kind == kindStruct:
			size, err := g.byValueSize(fs, p, a)
			if err != nil {
				return nil, fmt.Errorf("parameter %s: %w", p.name, err)
			}
			f.params = append(f.params, p)
			f.shapes = append(f.shapes, shapeOther)
			f.byValue = append(f.byValue, size)
			continue
		case p.typ.size > a.ptrSize():
			return nil, fmt.Errorf("parameter %s is larger than a pointer", p.name)
		}
		name := p.typ.name
		if o, ok := fs.params[p.name]; ok {
			name = o
		} else if p.typ.undefined {
			return nil, fmt.Errorf("parameter %s: %s refers to a struct the Go package does not define", p.name, name)
		}
		sh := g.pkg.shapeOf(name)
		if err := g.checkShape(p.typ, name, sh); err != nil {
			return nil, fmt.Errorf("parameter %s: %w", p.name, err)
		}
		p.typ.name = name
		f.params = append(f.params, p)
		f.shapes = append(f.shapes, sh)
		f.byValue = append(f.byValue, 0)
	}

	r := sig.result
	switch {
	case r.kind == kindVoid:
		if fs.result != "" {
			return nil, fmt.Errorf("function has no result")
		}
		return f, nil
	case r.kind == kindFloat:
		return nil, fmt.Errorf("result is a floating-point value")
	case r.kind == kindStruct:
		return nil, fmt.Errorf("result is a struct")
	case r.size > a.ptrSize():
		return nil, fmt.Errorf("result is larger than a pointer")
	}
	f.result = r.name
	if fs.result != "" {
		f.result = fs.result
	} else if r.undefined {
		return nil, fmt.Errorf("result: %s refers to a struct the Go package does not define", r.name)
	}
	f.rshape = g.pkg.shapeOf(f.result)
	if err := g.checkShape(r, f.result, f.rshape); err != nil {
		return nil, fmt.Errorf("result: %w", err)
	}
	if f.rshape == shapePointer {
		// Converting the uintptr result back to a pointer is not allowed
		// by the unsafe.Pointer rules.
		return nil, fmt.Errorf("result %s is a pointer", f.result)
	}
	return f, nil
}

// byValueSize returns the size of a struct parameter passed by value. Only
// structs of 1, 2 or 4 bytes without floating-point fields are supported:
// the calling conventions of all architectures pass them like an integer
// of the same size in a single register or stack slot. The Go struct must
// be generated, so that its layout is checked against the metadata.
func (g *generator) byValueSize(fs *funcSpec, p param, a arch) (int, error) {
	if _, ok := fs.params[p.name]; ok {
		return 0, fmt.Errorf("the type of a struct passed by value cannot be overridden")
	}
	generated := false
	for _, ss := range g.s.structs {
		generated = generated || ss.name == p.typ.name
	}
	if !generated {
		return 0, fmt.Errorf("struct %s passed by value is not generated", p.typ.name)
	}
	l, err := g.m.layoutOf(p.meta, a, cRules)
	if err != nil {
		return 0, err
	}
	if l.size != 1 && l.size != 2 && l.size != 4 {
		return 0, fmt.Errorf("struct %s of %d bytes is passed by value", p.typ.name, l.size)
	}
	if hasFloat, err := g.m.hasFloat(p.meta, a); err != nil || hasFloat {
		return 0, fmt.Errorf("struct %s with floating-point fields is passed by value", p.typ.name)
	}
	return l.size, nil
}

// checkShape checks that a Go type with the given shape can stand for a
// metadata type.
func (g *generator) checkShape(t goType, name string, sh shape) error {
	switch t.kind {
	case kindPointer, kindInterface:
		// Handles are pointers in the metadata and uintptr values in Go.
		if sh == shapePointer || g.pkg.basic(name) == "uintptr" {
			return nil
		}
	case kindScalar:
		if sh == shapeScalar || (sh == shapeBool && t.size == 4) {
			return nil
		}
	case kindBool:
		if sh == shapeBool || sh == shapeScalar {
			return nil
		}
	}
	return fmt.Errorf("Go type %s cannot stand for %s", name, t.name)
}

func goParamName(name string) string {
	switch {
	case token.IsKeyword(name), name == "syscall", name == "unsafe", name == "windows",
		name == "r1", name == "BoolToBOOL", name == "uintptr":
		return name + "_"
	}
	return name
}

func (g *generator) writeFunc(b *bytes.Buffer, f *genFunc) {
	var params []string
	for _, p := range f.params {
		params = append(params, p.name+" "+p.typ.name)
	}
	fmt.Fprintf(b, "func %s(%s) %s {\n", f.spec.name, strings.Join(params, ", "), f.result)

	args := []string{f.proc + ".Addr()"}
	for i, p := range f.params {
		switch {
		case f.byValue[i] > 0:
			args = append(args, fmt.Sprintf("uintptr(*(*uint%d)(unsafe.Pointer(&%s)))", 8*f.byValue[i], p.name))
		case f.shapes[i] == shapeBool:
			args = append(args, "uintptr(BoolToBOOL("+p.name+"))")
		case p.typ.name == "uintptr":
			args = append(args, p.name)
		case p.typ.name == "unsafe.Pointer":
			args = append(args, "uintptr("+p.name+")")
		case f.shapes[i] == shapePointer:
			args = append(args, "uintptr(unsafe.Pointer("+p.name+"))")
		default:
			args = append(args, "uintptr("+p.name+")")
		}
	}
	call := "syscall.SyscallN(" + strings.Join(args, ", ") + ")"
	switch {
	case f.result == "":
		fmt.Fprintf(b, "\t%s\n", call)
	case f.rshape == shapeBool:
		fmt.Fprintf(b, "\tr1, _, _ := %s\n\treturn r1 != 0\n", call)
	case f.result == "uintptr":
		fmt.Fprintf(b, "\tr1, _, _ := %s\n\treturn r1\n", call)
	default:
		fmt.Fprintf(b, "\tr1, _, _ := %s\n\treturn %s(r1)\n", call, f.result)
	}
	b.WriteString("}\n\n")
}

// formatSource formats generated code, reporting syntax errors with the
// source for debugging.
func formatSource(name string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("%s: %v\n%s", name, err, src)
	}
	return out, nil
}
