// Copyright 2026 The Walk Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"
)

// outputPrefix starts the names of all generated files.
const outputPrefix = "zwinmd_"

type generator struct {
	m    *metadata
	s    *spec
	pkg  *goPackage
	errs []string
}

func (g *generator) errorf(line int, format string, args ...any) {
	g.errs = append(g.errs, fmt.Sprintf("line %d: %s", line, fmt.Sprintf(format, args...)))
}

func header(b *bytes.Buffer, s *spec, imports ...string) {
	fmt.Fprintf(b, "// Code generated by winmdgen from %s %s; DO NOT EDIT.\n\n", nugetPackage, s.metaVersion)
	b.WriteString("//go:build windows\n\npackage win\n\n")
	if len(imports) > 0 {
		b.WriteString("import (\n")
		std := true
		for _, imp := range imports {
			if std && strings.Contains(imp, ".") {
				b.WriteString("\n")
				std = false
			}
			fmt.Fprintf(b, "\t%q\n", imp)
		}
		b.WriteString(")\n\n")
	}
}

// constants generates the const declarations.
func (g *generator) constants() []byte {
	type entry struct {
		name, decl string
	}
	groups := make(map[string][]entry)
	for _, cs := range g.s.constants {
		c, err := g.m.lookupConstant(cs.name)
		if err != nil {
			g.errorf(cs.line, "%v", err)
			continue
		}
		value, err := c.goValue()
		if err != nil {
			g.errorf(cs.line, "%v", err)
			continue
		}
		decl := cs.name
		if cs.goType != "" {
			decl += " " + cs.goType
		}
		decl += " = " + value
		group := c.enum
		if group == "" {
			group = c.namespace
		}
		groups[group] = append(groups[group], entry{cs.name, decl})
	}

	var b bytes.Buffer
	header(&b, g.s)
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		entries := groups[k]
		sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })
		fmt.Fprintf(&b, "// %s\nconst (\n", k)
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%s\n", e.decl)
		}
		b.WriteString(")\n\n")
	}
	return b.Bytes()
}

func (m *metadata) lookupConstant(name string) (*constant, error) {
	cs := m.constants[name]
	if len(cs) == 0 {
		return nil, fmt.Errorf("constant %s not found in the metadata", name)
	}
	c := cs[0]
	for _, c2 := range cs[1:] {
		if c2.kind != c.kind || c2.ival != c.ival || c2.uval != c.uval || c2.fval != c.fval || c2.sval != c.sval {
			return nil, fmt.Errorf("constant %s has different values in %s and %s", name, c.namespace, c2.namespace)
		}
	}
	if c.arch != archAll {
		return nil, fmt.Errorf("constant %s is specific to %v", name, c.arch)
	}
	return c, nil
}

// goValue returns the value of a constant as a Go literal.
func (c *constant) goValue() (string, error) {
	if c.guid != nil {
		return "", fmt.Errorf("constant %s is a GUID", c.name)
	}
	if i, u, signed, ok := c.integer(); ok {
		switch {
		case signed && i < 0:
			return strconv.FormatInt(i, 10), nil
		case signed:
			u = uint64(i)
		}
		if u < 10 {
			return strconv.FormatUint(u, 10), nil
		}
		return "0x" + strconv.FormatUint(u, 16), nil
	}
	switch c.kind {
	case 0x0c, 0x0d: // R4, R8
		return strconv.FormatFloat(c.fval, 'g', -1, 64), nil
	case 0x0e: // STRING
		return strconv.Quote(c.sval), nil
	}
	return "", fmt.Errorf("constant %s has unsupported type %v", c.name, c.kind)
}

// genFunc is a function ready to be written.
type genFunc struct {
	spec   *funcSpec
	method *method
	params []param // with Go types and code shapes resolved
	shapes []shape
	result string
	rshape shape
}

// functions generates the DLL and procedure variables and the wrapper
// functions.
func (g *generator) functions() []byte {
	dlls := make(map[string]*dllSpec)
	for _, d := range g.s.dlls {
		dlls[d.name] = d
	}

	var funcs []*genFunc
	for _, fs := range g.s.functions {
		f, err := g.function(fs)
		if err != nil {
			g.errorf(fs.line, "%s: %v", fs.name, err)
			continue
		}
		if dlls[f.method.dll] == nil {
			g.errorf(fs.line, "%s: no dll directive for %s", fs.name, f.method.dll)
			continue
		}
		funcs = append(funcs, f)
	}
	sort.Slice(funcs, func(i, j int) bool { return funcs[i].spec.name < funcs[j].spec.name })

	var body bytes.Buffer
	for _, f := range funcs {
		g.writeFunc(&body, f)
	}

	var b bytes.Buffer
	imports := []string{"syscall"}
	if bytes.Contains(body.Bytes(), []byte("unsafe.")) {
		imports = append(imports, "unsafe")
	}
	header(&b, g.s, append(imports, "golang.org/x/sys/windows")...)
	b.WriteString("var (\n")
	// The DLL variables are also used by hand-written code.
	for _, d := range g.s.dlls {
		fmt.Fprintf(&b, "\t%s = windows.NewLazySystemDLL(%q)\n", d.goName, d.name)
	}
	b.WriteString("\n")
	for _, f := range funcs {
		fmt.Fprintf(&b, "\tproc%s = %s.NewProc(%q)\n", f.method.entry, dlls[f.method.dll].goName, f.method.entry)
	}
	b.WriteString(")\n\n")
	b.Write(body.Bytes())
	return b.Bytes()
}

// goSignature returns the Go parameter and result types.
func (f *genFunc) goSignature() string {
	var types []string
	for _, p := range f.params {
		types = append(types, p.typ.name)
	}
	return "(" + strings.Join(types, ", ") + ") " + f.result
}

func (g *generator) function(fs *funcSpec) (*genFunc, error) {
	var mds []*method
	if fs.entry != "" {
		mds = g.m.methods[fs.entry]
	} else if mds = g.m.methods[fs.name+"W"]; len(mds) == 0 {
		mds = g.m.methods[fs.name]
	}
	switch {
	case len(mds) == 0:
		return nil, fmt.Errorf("function not found in the metadata")
	case len(mds) > 1:
		return nil, fmt.Errorf("function has %d definitions in the metadata", len(mds))
	}
	md := mds[0]
	if md.arch != archAll {
		return nil, fmt.Errorf("function is specific to %v", md.arch)
	}
	if md.dll == "" {
		return nil, fmt.Errorf("function has no DLL import")
	}

	// The Go signature must be the same on all architectures.
	var f *genFunc
	for _, an := range archNames {
		tm := &typeMapper{m: g.m, arch: an.arch, pkg: g.pkg, rawBool: fs.rawBool}
		sig, err := tm.signature(md)
		if err != nil {
			return nil, err
		}
		af, err := g.project(fs, md, sig, an.arch)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", an.name, err)
		}
		if f == nil {
			f = af
			continue
		}
		if af.goSignature() != f.goSignature() {
			return nil, fmt.Errorf("signature differs between architectures")
		}
	}
	for name := range fs.params {
		found := false
		for _, p := range f.params {
			found = found || p.name == name
		}
		if !found {
			return nil, fmt.Errorf("no parameter %s", name)
		}
	}
	for i := range f.params {
		f.params[i].name = goParamName(f.params[i].name)
	}
	return f, nil
}

// project applies the overrides of the specification to a metadata
// signature and checks that the result can be passed through
// syscall.SyscallN unchanged.
func (g *generator) project(fs *funcSpec, md *method, sig *signature, a arch) (*genFunc, error) {
	f := &genFunc{spec: fs, method: md}
	for _, p := range sig.params {
		switch {
		case p.typ.kind == kindFloat:
			return nil, fmt.Errorf("parameter %s is a floating-point value", p.name)
		case p.typ.kind == kindStruct:
			return nil, fmt.Errorf("parameter %s is a struct passed by value", p.name)
		case p.typ.size > a.ptrSize():
			return nil, fmt.Errorf("parameter %s is larger than a pointer", p.name)
		}
		name := p.typ.name
		if o, ok := fs.params[p.name]; ok {
			name = o
		}
		sh := g.pkg.shapeOf(name)
		if err := g.checkShape(p.typ, name, sh); err != nil {
			return nil, fmt.Errorf("parameter %s: %w", p.name, err)
		}
		p.typ.name = name
		f.params = append(f.params, p)
		f.shapes = append(f.shapes, sh)
	}

	r := sig.result
	switch {
	case r.kind == kindVoid:
		if fs.result != "" {
			return nil, fmt.Errorf("function has no result")
		}
		return f, nil
	case r.kind == kindFloat:
		return nil, fmt.Errorf("result is a floating-point value")
	case r.kind == kindStruct:
		return nil, fmt.Errorf("result is a struct")
	case r.size > a.ptrSize():
		return nil, fmt.Errorf("result is larger than a pointer")
	}
	f.result = r.name
	if fs.result != "" {
		f.result = fs.result
	}
	f.rshape = g.pkg.shapeOf(f.result)
	if err := g.checkShape(r, f.result, f.rshape); err != nil {
		return nil, fmt.Errorf("result: %w", err)
	}
	if f.rshape == shapePointer {
		// Converting the uintptr result back to a pointer is not allowed
		// by the unsafe.Pointer rules.
		return nil, fmt.Errorf("result %s is a pointer", f.result)
	}
	return f, nil
}

// checkShape checks that a Go type with the given shape can stand for a
// metadata type.
func (g *generator) checkShape(t goType, name string, sh shape) error {
	switch t.kind {
	case kindPointer, kindInterface:
		// Handles are pointers in the metadata and uintptr values in Go.
		if sh == shapePointer || g.pkg.basic(name) == "uintptr" {
			return nil
		}
	case kindScalar:
		if sh == shapeScalar || (sh == shapeBool && t.size == 4) {
			return nil
		}
	case kindBool:
		if sh == shapeBool || sh == shapeScalar {
			return nil
		}
	}
	return fmt.Errorf("Go type %s cannot stand for %s", name, t.name)
}

func goParamName(name string) string {
	switch {
	case token.IsKeyword(name), name == "syscall", name == "unsafe", name == "windows",
		name == "r1", name == "BoolToBOOL", name == "uintptr":
		return name + "_"
	}
	return name
}

func (g *generator) writeFunc(b *bytes.Buffer, f *genFunc) {
	var params []string
	for _, p := range f.params {
		params = append(params, p.name+" "+p.typ.name)
	}
	fmt.Fprintf(b, "func %s(%s) %s {\n", f.spec.name, strings.Join(params, ", "), f.result)

	args := []string{"proc" + f.method.entry + ".Addr()"}
	for i, p := range f.params {
		switch {
		case f.shapes[i] == shapeBool:
			args = append(args, "uintptr(BoolToBOOL("+p.name+"))")
		case p.typ.name == "uintptr":
			args = append(args, p.name)
		case p.typ.name == "unsafe.Pointer":
			args = append(args, "uintptr("+p.name+")")
		case f.shapes[i] == shapePointer:
			args = append(args, "uintptr(unsafe.Pointer("+p.name+"))")
		default:
			args = append(args, "uintptr("+p.name+")")
		}
	}
	call := "syscall.SyscallN(" + strings.Join(args, ", ") + ")"
	switch {
	case f.result == "":
		fmt.Fprintf(b, "\t%s\n", call)
	case f.rshape == shapeBool:
		fmt.Fprintf(b, "\tr1, _, _ := %s\n\treturn r1 != 0\n", call)
	case f.result == "uintptr":
		fmt.Fprintf(b, "\tr1, _, _ := %s\n\treturn r1\n", call)
	default:
		fmt.Fprintf(b, "\tr1, _, _ := %s\n\treturn %s(r1)\n", call, f.result)
	}
	b.WriteString("}\n\n")
}

// formatSource formats generated code, reporting syntax errors with the
// source for debugging.
func formatSource(name string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("%s: %v\n%s", name, err, src)
	}
	return out, nil
}
