// Code generated by winmdgen from Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview; DO NOT EDIT.

//go:build windows

package win

// BACKGROUND_MODE
const (
	TRANSPARENT = 1
)

// BI_COMPRESSION
const (
	BI_BITFIELDS = 3
	BI_RGB       = 0
)

// BRUSH_STYLE
const (
	BS_DIBPATTERN = 5
	BS_HATCHED    = 2
	BS_NULL       = 1
	BS_SOLID      = 0
)

// BUTTONPARTS
const (
	BP_PUSHBUTTON = 1
)

// CLIPBOARD_FORMAT
const (
	CF_UNICODETEXT = 0xd
)

// CLSCTX
const (
	CLSCTX_ALL            = 0x17
	CLSCTX_INPROC_HANDLER = 2
	CLSCTX_INPROC_SERVER  = 1
)

// COMBOBOXINFO_BUTTON_STATE
const (
	STATE_SYSTEM_FOCUSABLE   = 0x100000
	STATE_SYSTEM_INVISIBLE   = 0x8000
	STATE_SYSTEM_OFFSCREEN   = 0x10000
	STATE_SYSTEM_PRESSED     = 8
	STATE_SYSTEM_UNAVAILABLE = 1
)

// CommandStateChangeConstants
const (
	CSC_NAVIGATEBACK    = 2
	CSC_NAVIGATEFORWARD = 1
	CSC_UPDATECOMMANDS  = -1
)

// DIB_USAGE
const (
	DIB_RGB_COLORS = 0
)

// DI_FLAGS
const (
	DI_NORMAL = 3
)

// DLG_BUTTON_CHECK_STATE
const (
	BST_CHECKED       = 1
	BST_INDETERMINATE = 2
	BST_UNCHECKED     = 0
)

// DOCHOSTUIDBLCLK
const (
	DOCHOSTUIDBLCLK_DEFAULT = 0
)

// DOCHOSTUIFLAG
const (
	DOCHOSTUIFLAG_NO3DBORDER = 4
)

// DRAW_TEXT_FORMAT
const (
	DT_BOTTOM               = 8
	DT_CALCRECT             = 0x400
	DT_CENTER               = 1
	DT_EDITCONTROL          = 0x2000
	DT_END_ELLIPSIS         = 0x8000
	DT_EXPANDTABS           = 0x40
	DT_EXTERNALLEADING      = 0x200
	DT_HIDEPREFIX           = 0x100000
	DT_INTERNAL             = 0x1000
	DT_LEFT                 = 0
	DT_MODIFYSTRING         = 0x10000
	DT_NOCLIP               = 0x100
	DT_NOFULLWIDTHCHARBREAK = 0x80000
	DT_NOPREFIX             = 0x800
	DT_PATH_ELLIPSIS        = 0x4000
	DT_PREFIXONLY           = 0x200000
	DT_RIGHT                = 2
	DT_RTLREADING           = 0x20000
	DT_SINGLELINE           = 0x20
	DT_TABSTOP              = 0x80
	DT_TOP                  = 0
	DT_VCENTER              = 4
	DT_WORDBREAK            = 0x10
	DT_WORD_ELLIPSIS        = 0x40000
)

// DTTOPTS_FLAGS
const (
	DTT_GLOWSIZE = 0x800
)

// EDITBALLOONTIP_ICON
const (
	TTI_ERROR   = 3
	TTI_INFO    = 1
	TTI_NONE    = 0
	TTI_WARNING = 2
)

// FONT_CHARSET
const (
	DEFAULT_CHARSET = 1
)

// FONT_CLIP_PRECISION
const (
	CLIP_DEFAULT_PRECIS = 0
)

// FONT_FAMILY
const (
	FF_SWISS = 0x20
)

// FONT_OUTPUT_PRECISION
const (
	OUT_TT_PRECIS = 4
)

// FONT_PITCH
const (
	VARIABLE_PITCH = 2
)

// FONT_QUALITY
const (
	CLEARTYPE_QUALITY = 5
)

// FONT_WEIGHT
const (
	FW_BOLD   = 0x2bc
	FW_NORMAL = 0x190
)

// GDI_IMAGE_TYPE
const (
	IMAGE_BITMAP = 0
	IMAGE_ICON   = 1
)

// GET_ANCESTOR_FLAGS
const (
	GA_PARENT = 1
	GA_ROOT   = 2
)

// GET_DEVICE_CAPS_INDEX
const (
	HORZRES    = 8
	LOGPIXELSX = 0x58
	LOGPIXELSY = 0x5a
	VERTRES    = 0xa
)

// GET_WINDOW_CMD
const (
	GW_CHILD = 5
)

// GLOBAL_ALLOC_FLAGS
const (
	GHND          = 0x42
	GMEM_FIXED    = 0
	GMEM_MOVEABLE = 2
)

// GRADIENT_FILL
const (
	GRADIENT_FILL_TRIANGLE = 2
)

// HATCH_BRUSH_STYLE
const (
	HS_BDIAGONAL  = 3
	HS_CROSS      = 4
	HS_DIAGCROSS  = 5
	HS_FDIAGONAL  = 2
	HS_HORIZONTAL = 0
	HS_VERTICAL   = 1
)

// HDI_MASK
const (
	HDI_FORMAT = 4
)

// HEADER_CONTROL_FORMAT_FLAGS
const (
	HDF_SORTDOWN = 0x200
	HDF_SORTUP   = 0x400
)

// HIGHCONTRASTW_FLAGS
const (
	HCF_HIGHCONTRASTON = 1
)

// IMAGELIST_CREATION_FLAGS
const (
	ILC_COLOR32 = 0x20
	ILC_MASK    = 1
)

// IMAGE_FLAGS
const (
	LR_CREATEDIBSECTION = 0x2000
)

// IMAGE_LIST_DRAW_STYLE
const (
	ILD_NORMAL = 0
)

// INITCOMMONCONTROLSEX_ICC
const (
	ICC_LINK_CLASS       = 0x8000
	ICC_LISTVIEW_CLASSES = 1
	ICC_PROGRESS_CLASS   = 0x20
	ICC_TAB_CLASSES      = 8
	ICC_TREEVIEW_CLASSES = 2
)

// LISTITEMSTATES
const (
	LISS_HOT              = 2
	LISS_HOTSELECTED      = 6
	LISS_NORMAL           = 1
	LISS_SELECTED         = 3
	LISS_SELECTEDNOTFOCUS = 5
)

// LISTVIEWPARTS
const (
	LVP_LISTITEM = 1
)

// LIST_ITEM_FLAGS
const (
	LIF_ITEMINDEX = 1
	LIF_STATE     = 2
)

// LIST_ITEM_STATE_FLAGS
const (
	LIS_ENABLED = 2
	LIS_FOCUSED = 1
	LIS_VISITED = 4
)

// LIST_VIEW_ITEM_FLAGS
const (
	LVIF_IMAGE = 2
	LVIF_TEXT  = 1
)

// LIST_VIEW_ITEM_STATE_FLAGS
const (
	LVIS_FOCUSED        = 1
	LVIS_SELECTED       = 2
	LVIS_STATEIMAGEMASK = 0xf000
)

// LVCOLUMNW_MASK
const (
	LVCF_FMT     = 1
	LVCF_SUBITEM = 8
	LVCF_TEXT    = 4
	LVCF_WIDTH   = 2
)

// LVHITTESTINFO_FLAGS
const (
	LVHT_NOWHERE         = 1
	LVHT_ONITEMSTATEICON = 8
)

// MENUINFO_MASK
const (
	MIM_STYLE = 0x10
)

// MENUINFO_STYLE
const (
	MNS_CHECKORBMP = 0x4000000
)

// MENU_ITEM_FLAGS
const (
	MF_BYPOSITION = 0x400
)

// MENU_ITEM_MASK
const (
	MIIM_BITMAP     = 0x80
	MIIM_CHECKMARKS = 8
	MIIM_FTYPE      = 0x100
	MIIM_ID         = 2
	MIIM_STATE      = 1
	MIIM_STRING     = 0x40
	MIIM_SUBMENU    = 4
)

// MENU_ITEM_STATE
const (
	MFS_CHECKED  = 8
	MFS_DISABLED = 3
)

// MENU_ITEM_TYPE
const (
	MFT_RADIOCHECK = 0x200
	MFT_SEPARATOR  = 0x800
	MFT_STRING     = 0
)

// MESSAGEBOX_RESULT
const (
	IDABORT    = 3
	IDCANCEL   = 2
	IDCLOSE    = 8
	IDCONTINUE = 0xb
	IDHELP     = 9
	IDIGNORE   = 5
	IDNO       = 7
	IDOK       = 1
	IDRETRY    = 4
	IDTIMEOUT  = 0x7d00
	IDTRYAGAIN = 0xa
	IDYES      = 6
)

// MESSAGEBOX_STYLE
const (
	MB_ABORTRETRYIGNORE     = 2
	MB_APPLMODAL            = 0
	MB_CANCELTRYCONTINUE    = 6
	MB_DEFAULT_DESKTOP_ONLY = 0x20000
	MB_DEFBUTTON1           = 0
	MB_DEFBUTTON2           = 0x100
	MB_DEFBUTTON3           = 0x200
	MB_DEFBUTTON4           = 0x300
	MB_HELP                 = 0x4000
	MB_ICONASTERISK         = 0x40
	MB_ICONERROR            = 0x10
	MB_ICONEXCLAMATION      = 0x30
	MB_ICONHAND             = 0x10
	MB_ICONINFORMATION      = 0x40
	MB_ICONQUESTION         = 0x20
	MB_ICONSTOP             = 0x10
	MB_ICONWARNING          = 0x30
	MB_OK                   = 0
	MB_OKCANCEL             = 1
	MB_RETRYCANCEL          = 5
	MB_RIGHT                = 0x80000
	MB_RTLREADING           = 0x100000
	MB_SERVICE_NOTIFICATION = 0x200000
	MB_SETFOREGROUND        = 0x10000
	MB_SYSTEMMODAL          = 0x1000
	MB_TASKMODAL            = 0x2000
	MB_TOPMOST              = 0x40000
	MB_USERICON             = 0x80
	MB_YESNO                = 4
	MB_YESNOCANCEL          = 3
)

// MODIFIERKEYS_FLAGS
const (
	MK_LBUTTON = 1
	MK_MBUTTON = 0x10
	MK_RBUTTON = 2
)

// MONITOR_FROM_FLAGS
const (
	MONITOR_DEFAULTTOPRIMARY = 1
)

// NMCUSTOMDRAW_DRAW_STAGE
const (
	CDDS_ITEMPOSTPAINT = 0x10002
	CDDS_ITEMPREPAINT  = 0x10001
	CDDS_PREPAINT      = 1
	CDDS_SUBITEM       = 0x20000
)

// NMDATETIMECHANGE_FLAGS
const (
	GDT_NONE  = 1
	GDT_VALID = 0
)

// NM_TREEVIEW_ACTION
const (
	TVE_COLLAPSE      = 1
	TVE_COLLAPSERESET = 0x8000
	TVE_EXPAND        = 2
	TVE_EXPANDPARTIAL = 0x4000
	TVE_TOGGLE        = 3
)

// NOTIFY_ICON_DATA_FLAGS
const (
	NIF_ICON    = 2
	NIF_INFO    = 0x10
	NIF_MESSAGE = 1
	NIF_STATE   = 8
	NIF_TIP     = 4
)

// NOTIFY_ICON_INFOTIP_FLAGS
const (
	NIIF_ERROR   = 3
	NIIF_INFO    = 1
	NIIF_NONE    = 0
	NIIF_USER    = 4
	NIIF_WARNING = 2
)

// NOTIFY_ICON_MESSAGE
const (
	NIM_ADD        = 0
	NIM_DELETE     = 2
	NIM_MODIFY     = 1
	NIM_SETVERSION = 4
)

// NOTIFY_ICON_STATE
const (
	NIS_HIDDEN = 1
)

// OBJECT_IDENTIFIER
const (
	OBJID_CLIENT int32 = -4
)

// ODA_FLAGS
const (
	ODA_DRAWENTIRE = 1
)

// OLECLOSE
const (
	OLECLOSE_NOSAVE = 1
)

// OLEIVERB
const (
	OLEIVERB_SHOW = -1
)

// OPEN_FILENAME_FLAGS
const (
	OFN_ALLOWMULTISELECT = 0x200
	OFN_EXPLORER         = 0x80000
	OFN_FILEMUSTEXIST    = 0x1000
	OFN_HIDEREADONLY     = 4
	OFN_NOCHANGEDIR      = 8
)

// PEN_STYLE
const (
	PS_ALTERNATE     = 8
	PS_COSMETIC      = 0
	PS_DASH          = 1
	PS_DASHDOT       = 3
	PS_DASHDOTDOT    = 4
	PS_DOT           = 2
	PS_ENDCAP_FLAT   = 0x200
	PS_ENDCAP_ROUND  = 0
	PS_ENDCAP_SQUARE = 0x100
	PS_GEOMETRIC     = 0x10000
	PS_INSIDEFRAME   = 6
	PS_JOIN_BEVEL    = 0x1000
	PS_JOIN_MITER    = 0x2000
	PS_JOIN_ROUND    = 0
	PS_NULL          = 5
	PS_SOLID         = 0
	PS_USERSTYLE     = 7
)

// PUSHBUTTONSTATES
const (
	PBS_NORMAL = 1
)

// REG_SAM_FLAGS
const (
	KEY_READ REGSAM = 0x20019
)

// RGN_COMBINE_MODE
const (
	RGN_DIFF = 4
	RGN_OR   = 2
)

// ROP_CODE
const (
	SRCCOPY = 0xcc0020
)

// SCROLLBAR_COMMAND
const (
	SB_ENDSCROLL     = 8
	SB_LINEDOWN      = 1
	SB_LINELEFT      = 0
	SB_LINERIGHT     = 1
	SB_LINEUP        = 0
	SB_PAGEDOWN      = 3
	SB_PAGELEFT      = 2
	SB_PAGERIGHT     = 3
	SB_PAGEUP        = 2
	SB_THUMBPOSITION = 4
	SB_THUMBTRACK    = 5
)

// SCROLLBAR_CONSTANTS
const (
	SB_HORZ = 0
	SB_VERT = 1
)

// SCROLLINFO_MASK
const (
	SIF_PAGE     = 2
	SIF_POS      = 4
	SIF_RANGE    = 1
	SIF_TRACKPOS = 0x10
)

// SET_WINDOW_POS_FLAGS
const (
	SWP_FRAMECHANGED  = 0x20
	SWP_NOACTIVATE    = 0x10
	SWP_NOMOVE        = 2
	SWP_NOOWNERZORDER = 0x200
	SWP_NOSIZE        = 1
	SWP_NOZORDER      = 4
	SWP_SHOWWINDOW    = 0x40
)

// SHGFI_FLAGS
const (
	SHGFI_SMALLICON    = 1
	SHGFI_SYSICONINDEX = 0x4000
)

// SHOW_WINDOW_CMD
const (
	SW_HIDE   = 0
	SW_SHOW   = 5
	SW_SHOWNA = 8
)

// STATIC_STYLES
const (
	SS_CENTER       = 1
	SS_ENDELLIPSIS  = 0x4000
	SS_ETCHEDHORZ   = 0x10
	SS_LEFT         = 0
	SS_NOPREFIX     = 0x80
	SS_NOTIFY       = 0x100
	SS_PATHELLIPSIS = 0x8000
	SS_RIGHT        = 2
)

// STRETCH_BLT_MODE
const (
	HALFTONE = 4
)

// SYSTEM_METRICS_INDEX
const (
	SM_CXSMICON  = 0x31
	SM_CXVSCROLL = 2
	SM_CYCAPTION = 4
	SM_CYHSCROLL = 3
	SM_CYICON    = 0xc
	SM_CYSMICON  = 0x32
)

// SYSTEM_PARAMETERS_INFO_ACTION
const (
	SPI_GETHIGHCONTRAST = 0x42
)

// SYS_COLOR_INDEX
const (
	COLOR_3DDKSHADOW              = 0x15
	COLOR_3DFACE                  = 0xf
	COLOR_3DHIGHLIGHT             = 0x14
	COLOR_3DLIGHT                 = 0x16
	COLOR_3DSHADOW                = 0x10
	COLOR_ACTIVEBORDER            = 0xa
	COLOR_ACTIVECAPTION           = 2
	COLOR_APPWORKSPACE            = 0xc
	COLOR_BACKGROUND              = 1
	COLOR_BTNFACE                 = 0xf
	COLOR_BTNHIGHLIGHT            = 0x14
	COLOR_BTNSHADOW               = 0x10
	COLOR_BTNTEXT                 = 0x12
	COLOR_CAPTIONTEXT             = 9
	COLOR_DESKTOP                 = 1
	COLOR_GRADIENTACTIVECAPTION   = 0x1b
	COLOR_GRADIENTINACTIVECAPTION = 0x1c
	COLOR_GRAYTEXT                = 0x11
	COLOR_HIGHLIGHT               = 0xd
	COLOR_HIGHLIGHTTEXT           = 0xe
	COLOR_HOTLIGHT                = 0x1a
	COLOR_INACTIVEBORDER          = 0xb
	COLOR_INACTIVECAPTION         = 3
	COLOR_INACTIVECAPTIONTEXT     = 0x13
	COLOR_INFOBK                  = 0x18
	COLOR_INFOTEXT                = 0x17
	COLOR_MENU                    = 4
	COLOR_MENUTEXT                = 7
	COLOR_SCROLLBAR               = 0
	COLOR_WINDOW                  = 5
	COLOR_WINDOWFRAME             = 6
	COLOR_WINDOWTEXT              = 8
)

// Status
const (
	Ok GpStatus = 0
)

// TABITEMSTATES
const (
	TIS_SELECTED = 3
)

// TBBUTTONINFOW_MASK
const (
	TBIF_IMAGE = 1
	TBIF_STATE = 4
	TBIF_STYLE = 8
	TBIF_TEXT  = 2
)

// TBPFLAG
const (
	TBPF_ERROR         = 4
	TBPF_INDETERMINATE = 1
	TBPF_NOPROGRESS    = 0
	TBPF_NORMAL        = 2
	TBPF_PAUSED        = 8
)

// TCITEMHEADERA_MASK
const (
	TCIF_IMAGE = 2
	TCIF_TEXT  = 1
)

// THEME_PROPERTY_SYMBOL_ID
const (
	TMT_FILLCOLOR = 0xeda
	TMT_TEXTCOLOR = 0xedb
)

// TOOLTIP_FLAGS
const (
	TTF_IDISHWND = 1
	TTF_SUBCLASS = 0x10
	TTF_TRACK    = 0x20
)

// TRACKMOUSEEVENT_FLAGS
const (
	TME_LEAVE = 2
)

// TRACK_POPUP_MENU_FLAGS
const (
	TPM_NOANIMATION = 0x4000
	TPM_RETURNCMD   = 0x100
)

// TREE_VIEW_ITEM_STATE_FLAGS
const (
	TVIS_EXPANDED = 0x20
)

// TVITEMEXW_CHILDREN
const (
	I_CHILDRENCALLBACK = -1
)

// TVITEM_MASK
const (
	TVIF_CHILDREN      = 0x40
	TVIF_IMAGE         = 2
	TVIF_SELECTEDIMAGE = 0x20
	TVIF_STATE         = 8
	TVIF_TEXT          = 1
)

// VARENUM
const (
	VT_ARRAY VARTYPE = 0x2000
	VT_UI1   VARTYPE = 0x11
)

// VIRTUAL_KEY
const (
	VK_ACCEPT              = 0x1e
	VK_ADD                 = 0x6b
	VK_APPS                = 0x5d
	VK_ATTN                = 0xf6
	VK_BACK                = 8
	VK_BROWSER_BACK        = 0xa6
	VK_BROWSER_FAVORITES   = 0xab
	VK_BROWSER_FORWARD     = 0xa7
	VK_BROWSER_HOME        = 0xac
	VK_BROWSER_REFRESH     = 0xa8
	VK_BROWSER_SEARCH      = 0xaa
	VK_BROWSER_STOP        = 0xa9
	VK_CANCEL              = 3
	VK_CAPITAL             = 0x14
	VK_CLEAR               = 0xc
	VK_CONTROL             = 0x11
	VK_CONVERT             = 0x1c
	VK_CRSEL               = 0xf7
	VK_DECIMAL             = 0x6e
	VK_DELETE              = 0x2e
	VK_DIVIDE              = 0x6f
	VK_DOWN                = 0x28
	VK_END                 = 0x23
	VK_EREOF               = 0xf9
	VK_ESCAPE              = 0x1b
	VK_EXECUTE             = 0x2b
	VK_EXSEL               = 0xf8
	VK_F1                  = 0x70
	VK_F10                 = 0x79
	VK_F11                 = 0x7a
	VK_F12                 = 0x7b
	VK_F13                 = 0x7c
	VK_F14                 = 0x7d
	VK_F15                 = 0x7e
	VK_F16                 = 0x7f
	VK_F17                 = 0x80
	VK_F18                 = 0x81
	VK_F19                 = 0x82
	VK_F2                  = 0x71
	VK_F20                 = 0x83
	VK_F21                 = 0x84
	VK_F22                 = 0x85
	VK_F23                 = 0x86
	VK_F24                 = 0x87
	VK_F3                  = 0x72
	VK_F4                  = 0x73
	VK_F5                  = 0x74
	VK_F6                  = 0x75
	VK_F7                  = 0x76
	VK_F8                  = 0x77
	VK_F9                  = 0x78
	VK_FINAL               = 0x18
	VK_HANGUL              = 0x15
	VK_HANJA               = 0x19
	VK_HELP                = 0x2f
	VK_HOME                = 0x24
	VK_INSERT              = 0x2d
	VK_JUNJA               = 0x17
	VK_KANA                = 0x15
	VK_KANJI               = 0x19
	VK_LAUNCH_APP1         = 0xb6
	VK_LAUNCH_APP2         = 0xb7
	VK_LAUNCH_MAIL         = 0xb4
	VK_LAUNCH_MEDIA_SELECT = 0xb5
	VK_LBUTTON             = 1
	VK_LCONTROL            = 0xa2
	VK_LEFT                = 0x25
	VK_LMENU               = 0xa4
	VK_LSHIFT              = 0xa0
	VK_LWIN                = 0x5b
	VK_MBUTTON             = 4
	VK_MEDIA_NEXT_TRACK    = 0xb0
	VK_MEDIA_PLAY_PAUSE    = 0xb3
	VK_MEDIA_PREV_TRACK    = 0xb1
	VK_MEDIA_STOP          = 0xb2
	VK_MENU                = 0x12
	VK_MODECHANGE          = 0x1f
	VK_MULTIPLY            = 0x6a
	VK_NEXT                = 0x22
	VK_NONAME              = 0xfc
	VK_NONCONVERT          = 0x1d
	VK_NUMLOCK             = 0x90
	VK_NUMPAD0             = 0x60
	VK_NUMPAD1             = 0x61
	VK_NUMPAD2             = 0x62
	VK_NUMPAD3             = 0x63
	VK_NUMPAD4             = 0x64
	VK_NUMPAD5             = 0x65
	VK_NUMPAD6             = 0x66
	VK_NUMPAD7             = 0x67
	VK_NUMPAD8             = 0x68
	VK_NUMPAD9             = 0x69
	VK_OEM_1               = 0xba
	VK_OEM_102             = 0xe2
	VK_OEM_2               = 0xbf
	VK_OEM_3               = 0xc0
	VK_OEM_4               = 0xdb
	VK_OEM_5               = 0xdc
	VK_OEM_6               = 0xdd
	VK_OEM_7               = 0xde
	VK_OEM_8               = 0xdf
	VK_OEM_CLEAR           = 0xfe
	VK_OEM_COMMA           = 0xbc
	VK_OEM_MINUS           = 0xbd
	VK_OEM_PERIOD          = 0xbe
	VK_OEM_PLUS            = 0xbb
	VK_PA1                 = 0xfd
	VK_PACKET              = 0xe7
	VK_PAUSE               = 0x13
	VK_PLAY                = 0xfa
	VK_PRINT               = 0x2a
	VK_PRIOR               = 0x21
	VK_PROCESSKEY          = 0xe5
	VK_RBUTTON             = 2
	VK_RCONTROL            = 0xa3
	VK_RETURN              = 0xd
	VK_RIGHT               = 0x27
	VK_RMENU               = 0xa5
	VK_RSHIFT              = 0xa1
	VK_RWIN                = 0x5c
	VK_SCROLL              = 0x91
	VK_SELECT              = 0x29
	VK_SEPARATOR           = 0x6c
	VK_SHIFT               = 0x10
	VK_SLEEP               = 0x5f
	VK_SNAPSHOT            = 0x2c
	VK_SPACE               = 0x20
	VK_SUBTRACT            = 0x6d
	VK_TAB                 = 9
	VK_UP                  = 0x26
	VK_VOLUME_DOWN         = 0xae
	VK_VOLUME_MUTE         = 0xad
	VK_VOLUME_UP           = 0xaf
	VK_XBUTTON1            = 5
	VK_XBUTTON2            = 6
	VK_ZOOM                = 0xfb
)

// WIN32_ERROR
const (
	ERROR_INVALID_PARAMETER = 0x57
	ERROR_SUCCESS           = 0
)

// WINDOW_EX_STYLE
const (
	WS_EX_CLIENTEDGE    = 0x200
	WS_EX_COMPOSITED    = 0x2000000
	WS_EX_CONTROLPARENT = 0x10000
	WS_EX_LAYOUTRTL     = 0x400000
	WS_EX_RTLREADING    = 0x2000
)

// WINDOW_LONG_PTR_INDEX
const (
	GWLP_USERDATA  = -21
	GWLP_WNDPROC   = -4
	GWL_EXSTYLE    = -20
	GWL_HWNDPARENT = -8
	GWL_ID         = -12
	GWL_STYLE      = -16
)

// WINDOW_MESSAGE_FILTER_ACTION
const (
	MSGFLT_ALLOW = 1
)

// WINDOW_STYLE
const (
	WS_BORDER           = 0x800000
	WS_CAPTION          = 0xc00000
	WS_CHILD            = 0x40000000
	WS_CLIPCHILDREN     = 0x2000000
	WS_CLIPSIBLINGS     = 0x4000000
	WS_DISABLED         = 0x8000000
	WS_GROUP            = 0x20000
	WS_HSCROLL          = 0x100000
	WS_OVERLAPPEDWINDOW = 0xcf0000
	WS_POPUP            = 0x80000000
	WS_SYSMENU          = 0x80000
	WS_TABSTOP          = 0x10000
	WS_THICKFRAME       = 0x40000
	WS_VISIBLE          = 0x10000000
	WS_VSCROLL          = 0x200000
)

// WORD_BREAK_ACTION
const (
	WB_ISDELIMITER = 2
	WB_LEFT        = 0
	WB_RIGHT       = 1
)

// Windows.Win32.Foundation
const (
	FALSE                      = 0
	MAX_PATH                   = 0x104
	S_FALSE                    = 1
	S_OK                       = 0
	TRUE                       = 1
	VARIANT_FALSE VARIANT_BOOL = 0
	VARIANT_TRUE  VARIANT_BOOL = -1
)

// Windows.Win32.Globalization
const (
	LOCALE_SDECIMAL     LCTYPE = 0xe
	LOCALE_STHOUSAND    LCTYPE = 0xf
	LOCALE_USER_DEFAULT LCID   = 0x400
)

// Windows.Win32.Graphics.Gdi
const (
	AC_SRC_ALPHA = 1
	CLR_INVALID  = 0xffffffff
)

// Windows.Win32.UI.Accessibility
const (
	ROLE_SYSTEM_ALERT              = 8
	ROLE_SYSTEM_ANIMATION          = 0x36
	ROLE_SYSTEM_APPLICATION        = 0xe
	ROLE_SYSTEM_BORDER             = 0x13
	ROLE_SYSTEM_BUTTONDROPDOWN     = 0x38
	ROLE_SYSTEM_BUTTONDROPDOWNGRID = 0x3a
	ROLE_SYSTEM_BUTTONMENU         = 0x39
	ROLE_SYSTEM_CARET              = 7
	ROLE_SYSTEM_CELL               = 0x1d
	ROLE_SYSTEM_CHARACTER          = 0x20
	ROLE_SYSTEM_CHART              = 0x11
	ROLE_SYSTEM_CHECKBUTTON        = 0x2c
	ROLE_SYSTEM_CLIENT             = 0xa
	ROLE_SYSTEM_CLOCK              = 0x3d
	ROLE_SYSTEM_COLUMN             = 0x1b
	ROLE_SYSTEM_COLUMNHEADER       = 0x19
	ROLE_SYSTEM_COMBOBOX           = 0x2e
	ROLE_SYSTEM_CURSOR             = 6
	ROLE_SYSTEM_DIAGRAM            = 0x35
	ROLE_SYSTEM_DIAL               = 0x31
	ROLE_SYSTEM_DIALOG             = 0x12
	ROLE_SYSTEM_DOCUMENT           = 0xf
	ROLE_SYSTEM_DROPLIST           = 0x2f
	ROLE_SYSTEM_EQUATION           = 0x37
	ROLE_SYSTEM_GRAPHIC            = 0x28
	ROLE_SYSTEM_GRIP               = 4
	ROLE_SYSTEM_GROUPING           = 0x14
	ROLE_SYSTEM_HELPBALLOON        = 0x1f
	ROLE_SYSTEM_HOTKEYFIELD        = 0x32
	ROLE_SYSTEM_INDICATOR          = 0x27
	ROLE_SYSTEM_IPADDRESS          = 0x3f
	ROLE_SYSTEM_LINK               = 0x1e
	ROLE_SYSTEM_LIST               = 0x21
	ROLE_SYSTEM_LISTITEM           = 0x22
	ROLE_SYSTEM_MENUBAR            = 2
	ROLE_SYSTEM_MENUITEM           = 0xc
	ROLE_SYSTEM_MENUPOPUP          = 0xb
	ROLE_SYSTEM_OUTLINE            = 0x23
	ROLE_SYSTEM_OUTLINEBUTTON      = 0x40
	ROLE_SYSTEM_OUTLINEITEM        = 0x24
	ROLE_SYSTEM_PAGETAB            = 0x25
	ROLE_SYSTEM_PAGETABLIST        = 0x3c
	ROLE_SYSTEM_PANE               = 0x10
	ROLE_SYSTEM_PROGRESSBAR        = 0x30
	ROLE_SYSTEM_PROPERTYPAGE       = 0x26
	ROLE_SYSTEM_PUSHBUTTON         = 0x2b
	ROLE_SYSTEM_RADIOBUTTON        = 0x2d
	ROLE_SYSTEM_ROW                = 0x1c
	ROLE_SYSTEM_ROWHEADER          = 0x1a
	ROLE_SYSTEM_SCROLLBAR          = 3
	ROLE_SYSTEM_SEPARATOR          = 0x15
	ROLE_SYSTEM_SLIDER             = 0x33
	ROLE_SYSTEM_SOUND              = 5
	ROLE_SYSTEM_SPINBUTTON         = 0x34
	ROLE_SYSTEM_SPLITBUTTON        = 0x3e
	ROLE_SYSTEM_STATICTEXT         = 0x29
	ROLE_SYSTEM_STATUSBAR          = 0x17
	ROLE_SYSTEM_TABLE              = 0x18
	ROLE_SYSTEM_TEXT               = 0x2a
	ROLE_SYSTEM_TITLEBAR           = 1
	ROLE_SYSTEM_TOOLBAR            = 0x16
	ROLE_SYSTEM_TOOLTIP            = 0xd
	ROLE_SYSTEM_WHITESPACE         = 0x3b
	ROLE_SYSTEM_WINDOW             = 9
	STATE_SYSTEM_HASPOPUP          = 0x40000000
	STATE_SYSTEM_NORMAL            = 0
)

// Windows.Win32.UI.Controls
const (
	BCM_GETIDEALSIZE                    = 0x1601
	BCN_DROPDOWN                        = 0xfffffb20
	BS_SPLITBUTTON                      = 0xc
	BTNS_AUTOSIZE                       = 0x10
	BTNS_CHECK                          = 2
	BTNS_DROPDOWN                       = 8
	BTNS_GROUP                          = 4
	BTNS_SEP                            = 1
	BTNS_SHOWTEXT                       = 0x40
	BTNS_WHOLEDROPDOWN                  = 0x80
	CCS_NODIVIDER                       = 0x40
	CCS_NORESIZE                        = 4
	CCS_VERT                            = 0x80
	CDRF_DODEFAULT                      = 0
	CDRF_NEWFONT                        = 2
	CDRF_NOTIFYITEMDRAW                 = 0x20
	CDRF_NOTIFYPOSTPAINT                = 0x10
	CDRF_NOTIFYSUBITEMDRAW              = 0x20
	CDRF_SKIPDEFAULT                    = 4
	CDRF_SKIPPOSTPAINT                  = 0x100
	DTM_GETRANGE                        = 0x1003
	DTM_GETSYSTEMTIME                   = 0x1001
	DTM_SETFORMAT                       = 0x1032
	DTM_SETRANGE                        = 0x1004
	DTM_SETSYSTEMTIME                   = 0x1002
	DTN_DATETIMECHANGE           uint32 = 0xfffffd09
	DTS_SHORTDATEFORMAT                 = 0
	DTS_SHOWNONE                        = 2
	EM_CHARFROMPOS                      = 0xd7
	EM_GETCARETINDEX                    = 0x1512
	EM_GETCUEBANNER                     = 0x1502
	EM_GETLIMITTEXT                     = 0xd5
	EM_GETLINECOUNT                     = 0xba
	EM_GETPASSWORDCHAR                  = 0xd2
	EM_GETRECT                          = 0xb2
	EM_GETSEL                           = 0xb0
	EM_GETWORDBREAKPROC                 = 0xd1
	EM_LIMITTEXT                        = 0xc5
	EM_POSFROMCHAR                      = 0xd6
	EM_REPLACESEL                       = 0xc2
	EM_SCROLLCARET                      = 0xb7
	EM_SETCUEBANNER                     = 0x1501
	EM_SETLIMITTEXT                     = 0xc5
	EM_SETPASSWORDCHAR                  = 0xcc
	EM_SETREADONLY                      = 0xcf
	EM_SETSEL                           = 0xb1
	EM_SETWORDBREAKPROC                 = 0xd0
	GDTR_MAX                            = 2
	GDTR_MIN                            = 1
	HDM_GETBITMAPMARGIN                 = 0x1215
	HDM_GETITEM                         = 0x120b
	HDM_GETITEMRECT                     = 0x1207
	HDM_HITTEST                         = 0x1206
	HDM_LAYOUT                          = 0x1205
	HDM_SETITEM                         = 0x120c
	HDS_NOSIZING                        = 0x800
	I_IMAGENONE                         = -2
	LM_GETIDEALSIZE                     = 0x701
	LM_GETITEM                          = 0x703
	LM_SETITEM                          = 0x702
	LVIR_BOUNDS                         = 0
	LVM_DELETECOLUMN                    = 0x101c
	LVM_ENSUREVISIBLE                   = 0x1013
	LVM_GETCALLBACKMASK                 = 0x100a
	LVM_GETCOLUMNORDERARRAY             = 0x103b
	LVM_GETCOLUMNWIDTH                  = 0x101d
	LVM_GETCOUNTPERPAGE                 = 0x1028
	LVM_GETEXTENDEDLISTVIEWSTYLE        = 0x1037
	LVM_GETHEADER                       = 0x101f
	LVM_GETITEMRECT                     = 0x100e
	LVM_GETITEMSTATE                    = 0x102c
	LVM_GETNEXTITEM                     = 0x100c
	LVM_GETSELECTEDCOUNT                = 0x1032
	LVM_GETSELECTIONMARK                = 0x1042
	LVM_GETTOPINDEX                     = 0x1027
	LVM_HITTEST                         = 0x1012
	LVM_INSERTCOLUMN                    = 0x1061
	LVM_ISITEMVISIBLE                   = 0x10b6
	LVM_REDRAWITEMS                     = 0x1015
	LVM_SCROLL                          = 0x1014
	LVM_SETBKCOLOR                      = 0x1001
	LVM_SETCALLBACKMASK                 = 0x100b
	LVM_SETCOLUMN                       = 0x1060
	LVM_SETCOLUMNORDERARRAY             = 0x103a
	LVM_SETCOLUMNWIDTH                  = 0x101e
	LVM_SETEXTENDEDLISTVIEWSTYLE        = 0x1036
	LVM_SETIMAGELIST                    = 0x1003
	LVM_SETITEMCOUNT                    = 0x102f
	LVM_SETITEMSTATE                    = 0x102b
	LVM_SETSELECTEDCOLUMN               = 0x108c
	LVM_UPDATE                          = 0x102a
	LVNI_SELECTED                       = 2
	LVN_BEGINSCROLL              uint32 = 0xffffff4c
	LVN_COLUMNCLICK              uint32 = 0xffffff94
	LVN_GETDISPINFO              uint32 = 0xffffff4f
	LVN_ITEMACTIVATE             uint32 = 0xffffff8e
	LVN_ITEMCHANGED              uint32 = 0xffffff9b
	LVN_ODSTATECHANGED           uint32 = 0xffffff8d
	LVSICF_NOINVALIDATEALL              = 1
	LVSICF_NOSCROLL                     = 2
	LVSIL_SMALL                         = 1
	LVS_EX_CHECKBOXES                   = 4
	LVS_EX_DOUBLEBUFFER                 = 0x10000
	LVS_EX_FULLROWSELECT                = 0x20
	LVS_EX_GRIDLINES                    = 1
	LVS_EX_HEADERDRAGDROP               = 0x10
	LVS_EX_LABELTIP                     = 0x4000
	LVS_EX_SUBITEMIMAGES                = 2
	LVS_NOCOLUMNHEADER                  = 0x4000
	LVS_NOSORTHEADER                    = 0x8000
	LVS_OWNERDATA                       = 0x1000
	LVS_OWNERDRAWFIXED                  = 0x400
	LVS_REPORT                          = 1
	LVS_SHOWSELALWAYS                   = 8
	LVS_SINGLESEL                       = 4
	NM_CLICK                     uint32 = 0xfffffffe
	NM_CUSTOMDRAW                uint32 = 0xfffffff4
	NM_DBLCLK                    uint32 = 0xfffffffd
	NM_RETURN                    uint32 = 0xfffffffc
	PBM_GETPOS                          = 0x408
	PBM_GETRANGE                        = 0x407
	PBM_SETMARQUEE                      = 0x40a
	PBM_SETPOS                          = 0x402
	PBM_SETRANGE32                      = 0x406
	PBS_MARQUEE                         = 8
	SBARS_SIZEGRIP                      = 0x100
	SBARS_TOOLTIPS                      = 0x800
	SB_SETICON                          = 0x40f
	SB_SETPARTS                         = 0x404
	SB_SETTEXT                          = 0x40b
	TBDDRET_DEFAULT                     = 0
	TBM_GETLINESIZE                     = 0x418
	TBM_GETPAGESIZE                     = 0x416
	TBM_GETRANGEMAX                     = 0x402
	TBM_GETRANGEMIN                     = 0x401
	TBM_SETLINESIZE                     = 0x417
	TBM_SETPAGESIZE                     = 0x415
	TBM_SETPOS                          = 0x405
	TBM_SETRANGEMAX                     = 0x408
	TBM_SETRANGEMIN                     = 0x407
	TBSTATE_CHECKED                     = 1
	TBSTATE_ENABLED                     = 4
	TBSTATE_WRAP                        = 0x20
	TBSTYLE_EX_DRAWDDARROWS             = 1
	TBSTYLE_EX_MIXEDBUTTONS             = 8
	TBSTYLE_FLAT                        = 0x800
	TBSTYLE_LIST                        = 0x1000
	TBSTYLE_TOOLTIPS                    = 0x100
	TBSTYLE_WRAPABLE                    = 0x200
	TBS_TOOLTIPS                        = 0x100
	TBS_VERT                            = 2
	TB_AUTOSIZE                         = 0x421
	TB_BUTTONSTRUCTSIZE                 = 0x41e
	TB_DELETEBUTTON                     = 0x416
	TB_ENDTRACK                         = 8
	TB_GETBUTTONSIZE                    = 0x43a
	TB_GETEXTENDEDSTYLE                 = 0x455
	TB_GETIDEALSIZE                     = 0x463
	TB_GETRECT                          = 0x433
	TB_INSERTBUTTON                     = 0x443
	TB_SETBUTTONINFO                    = 0x440
	TB_SETBUTTONSIZE                    = 0x41f
	TB_SETBUTTONWIDTH                   = 0x43b
	TB_SETEXTENDEDSTYLE                 = 0x454
	TB_SETIMAGELIST                     = 0x430
	TB_SETMAXTEXTROWS                   = 0x43c
	TB_THUMBPOSITION                    = 4
	TB_THUMBTRACK                       = 5
	TCM_ADJUSTRECT                      = 0x1328
	TCM_DELETEALLITEMS                  = 0x1309
	TCM_DELETEITEM                      = 0x1308
	TCM_GETCURSEL                       = 0x130b
	TCM_GETITEMRECT                     = 0x130a
	TCM_INSERTITEM                      = 0x133e
	TCM_SETCURSEL                       = 0x130c
	TCM_SETIMAGELIST                    = 0x1303
	TCM_SETITEM                         = 0x133d
	TTM_ADDTOOL                         = 0x432
	TTM_DELTOOL                         = 0x433
	TTM_GETTITLE                        = 0x423
	TTM_GETTOOLINFO                     = 0x435
	TTM_RELAYEVENT                      = 0x407
	TTM_SETMAXTIPWIDTH                  = 0x418
	TTM_SETTITLE                        = 0x421
	TTM_SETTOOLINFO                     = 0x436
	TTM_TRACKACTIVATE                   = 0x411
	TTM_TRACKPOSITION                   = 0x412
	TTS_ALWAYSTIP                       = 1
	TTS_BALLOON                         = 0x40
	TTS_NOPREFIX                        = 2
	TVGN_CARET                          = 9
	TVM_DELETEITEM                      = 0x1101
	TVM_ENSUREVISIBLE                   = 0x1114
	TVM_EXPAND                          = 0x1102
	TVM_GETITEM                         = 0x113e
	TVM_GETITEMHEIGHT                   = 0x111c
	TVM_HITTEST                         = 0x1111
	TVM_INSERTITEM                      = 0x1132
	TVM_SELECTITEM                      = 0x110b
	TVM_SETBKCOLOR                      = 0x111d
	TVM_SETEXTENDEDSTYLE                = 0x112c
	TVM_SETIMAGELIST                    = 0x1109
	TVM_SETITEM                         = 0x113f
	TVM_SETITEMHEIGHT                   = 0x111b
	TVN_GETDISPINFO              uint32 = 0xfffffe3c
	TVN_ITEMEXPANDED             uint32 = 0xfffffe39
	TVN_ITEMEXPANDING            uint32 = 0xfffffe3a
	TVN_KEYDOWN                  uint32 = 0xfffffe64
	TVN_SELCHANGED               uint32 = 0xfffffe3d
	TVS_EX_DOUBLEBUFFER                 = 4
	TVS_HASBUTTONS                      = 1
	TVS_LINESATROOT                     = 4
	TVS_SHOWSELALWAYS                   = 0x20
	TVS_TRACKSELECT                     = 0x200
	UDM_SETBUDDY                        = 0x469
	UDN_DELTAPOS                 uint32 = 0xfffffd2e
	UDS_ALIGNRIGHT                      = 4
	UDS_ARROWKEYS                       = 0x20
	UDS_HOTTRACK                        = 0x100
	WM_MOUSELEAVE                       = 0x2a3
)

// Windows.Win32.UI.Shell
const (
	CSIDL_APPDATA        = 0x1a
	CSIDL_COMMON_APPDATA = 0x23
	CSIDL_LOCAL_APPDATA  = 0x1c
	CSIDL_PERSONAL       = 5
	CSIDL_SYSTEM         = 0x25
	NIN_BALLOONUSERCLICK = 0x405
	NOTIFYICON_VERSION   = 3
)

// Windows.Win32.UI.WindowsAndMessaging
const (
	BM_GETCHECK                         = 0xf0
	BM_SETCHECK                         = 0xf1
	BM_SETIMAGE                         = 0xf7
	BN_CLICKED                          = 0
	BS_AUTO3STATE                       = 6
	BS_AUTOCHECKBOX                     = 3
	BS_AUTORADIOBUTTON                  = 9
	BS_BITMAP                           = 0x80
	BS_DEFPUSHBUTTON                    = 1
	BS_GROUPBOX                         = 7
	BS_LEFTTEXT                         = 0x20
	BS_PUSHBUTTON                       = 0
	BS_TOP                              = 0x400
	CBN_EDITCHANGE                      = 5
	CBN_SELCHANGE                       = 1
	CBN_SELENDCANCEL                    = 0xa
	CBN_SELENDOK                        = 9
	CBS_AUTOHSCROLL                     = 0x40
	CBS_DROPDOWN                        = 2
	CBS_DROPDOWNLIST                    = 3
	CB_DELETESTRING                     = 0x144
	CB_GETCURSEL                        = 0x147
	CB_GETDROPPEDSTATE                  = 0x157
	CB_GETEDITSEL                       = 0x140
	CB_INSERTSTRING                     = 0x14a
	CB_LIMITTEXT                        = 0x141
	CB_RESETCONTENT                     = 0x14b
	CB_SETCURSEL                        = 0x14e
	CB_SETEDITSEL                       = 0x142
	CHILDID_SELF                        = 0
	CW_USEDEFAULT                       = -2147483648
	DLGC_BUTTON                         = 0x2000
	DLGC_DEFPUSHBUTTON                  = 0x10
	DLGC_HASSETSEL                      = 8
	DLGC_WANTALLKEYS                    = 4
	DLGC_WANTARROWS                     = 1
	DLGC_WANTCHARS                      = 0x80
	EN_CHANGE                           = 0x300
	ES_AUTOHSCROLL                      = 0x80
	ES_CENTER                           = 1
	ES_LEFT                             = 0
	ES_LOWERCASE                        = 0x10
	ES_MULTILINE                        = 4
	ES_READONLY                         = 0x800
	ES_RIGHT                            = 2
	ES_UPPERCASE                        = 8
	ES_WANTRETURN                       = 0x1000
	EVENT_OBJECT_ACCELERATORCHANGE      = 0x8012
	EVENT_OBJECT_CREATE                 = 0x8000
	EVENT_OBJECT_DEFACTIONCHANGE        = 0x8011
	EVENT_OBJECT_DESCRIPTIONCHANGE      = 0x800d
	EVENT_OBJECT_END                    = 0x80ff
	EVENT_OBJECT_HELPCHANGE             = 0x8010
	EVENT_OBJECT_NAMECHANGE             = 0x800c
	EVENT_OBJECT_STATECHANGE            = 0x800a
	HTCLIENT                            = 1
	HWND_BOTTOM                    HWND = 1
	HWND_TOP                       HWND = 0
	IDC_APPSTARTING                     = 0x7f8a
	IDC_ARROW                           = 0x7f00
	IDC_CROSS                           = 0x7f03
	IDC_HAND                            = 0x7f89
	IDC_HELP                            = 0x7f8b
	IDC_IBEAM                           = 0x7f01
	IDC_ICON                            = 0x7f81
	IDC_NO                              = 0x7f88
	IDC_SIZE                            = 0x7f80
	IDC_SIZEALL                         = 0x7f86
	IDC_SIZENESW                        = 0x7f83
	IDC_SIZENS                          = 0x7f85
	IDC_SIZENWSE                        = 0x7f82
	IDC_SIZEWE                          = 0x7f84
	IDC_UPARROW                         = 0x7f04
	IDC_WAIT                            = 0x7f02
	IDI_APPLICATION                     = 0x7f00
	IDI_ERROR                           = 0x7f01
	IDI_INFORMATION                     = 0x7f04
	IDI_QUESTION                        = 0x7f02
	IDI_SHIELD                          = 0x7f06
	IDI_WARNING                         = 0x7f03
	IDI_WINLOGO                         = 0x7f05
	LBN_DBLCLK                          = 2
	LBN_SELCHANGE                       = 1
	LBS_EXTENDEDSEL                     = 0x800
	LBS_NOINTEGRALHEIGHT                = 0x100
	LBS_NOTIFY                          = 1
	LBS_OWNERDRAWVARIABLE               = 0x20
	LB_DELETESTRING                     = 0x182
	LB_ERR                              = -1
	LB_ERRSPACE                         = -2
	LB_GETCOUNT                         = 0x18b
	LB_GETCURSEL                        = 0x188
	LB_GETITEMRECT                      = 0x198
	LB_GETSELITEMS                      = 0x191
	LB_GETTOPINDEX                      = 0x18e
	LB_INSERTSTRING                     = 0x181
	LB_ITEMFROMPOINT                    = 0x1a9
	LB_RESETCONTENT                     = 0x184
	LB_SETCURSEL                        = 0x186
	LB_SETHORIZONTALEXTENT              = 0x194
	LB_SETITEMHEIGHT                    = 0x1a0
	LB_SETSEL                           = 0x185
	LB_SETTOPINDEX                      = 0x197
	PRF_CHILDREN                        = 0x10
	PRF_CLIENT                          = 4
	PRF_ERASEBKGND                      = 8
	PRF_NONCLIENT                       = 2
	PRF_OWNED                           = 0x20
	SC_CLOSE                            = 0xf060
	STATE_SYSTEM_ALERT_HIGH             = 0x10000000
	STATE_SYSTEM_ALERT_LOW              = 0x4000000
	STATE_SYSTEM_ALERT_MEDIUM           = 0x8000000
	STATE_SYSTEM_ANIMATED               = 0x4000
	STATE_SYSTEM_BUSY                   = 0x800
	STATE_SYSTEM_CHECKED                = 0x10
	STATE_SYSTEM_COLLAPSED              = 0x400
	STATE_SYSTEM_DEFAULT                = 0x100
	STATE_SYSTEM_EXPANDED               = 0x200
	STATE_SYSTEM_EXTSELECTABLE          = 0x2000000
	STATE_SYSTEM_FLOATING               = 0x1000
	STATE_SYSTEM_FOCUSED                = 4
	STATE_SYSTEM_HOTTRACKED             = 0x80
	STATE_SYSTEM_INDETERMINATE          = 0x20
	STATE_SYSTEM_LINKED                 = 0x400000
	STATE_SYSTEM_MARQUEED               = 0x2000
	STATE_SYSTEM_MIXED                  = 0x20
	STATE_SYSTEM_MOVEABLE               = 0x40000
	STATE_SYSTEM_MULTISELECTABLE        = 0x1000000
	STATE_SYSTEM_PROTECTED              = 0x20000000
	STATE_SYSTEM_READONLY               = 0x40
	STATE_SYSTEM_SELECTABLE             = 0x200000
	STATE_SYSTEM_SELECTED               = 2
	STATE_SYSTEM_SELFVOICING            = 0x80000
	STATE_SYSTEM_SIZEABLE               = 0x20000
	STATE_SYSTEM_TRAVERSED              = 0x800000
	UISF_HIDEFOCUS                      = 1
	UIS_CLEAR                           = 2
	UIS_INITIALIZE                      = 3
	UIS_SET                             = 1
	WA_ACTIVE                           = 1
	WA_CLICKACTIVE                      = 2
	WA_INACTIVE                         = 0
	WM_ACTIVATE                         = 6
	WM_APP                              = 0x8000
	WM_CHANGEUISTATE                    = 0x127
	WM_CHAR                             = 0x102
	WM_CLIPBOARDUPDATE                  = 0x31d
	WM_CLOSE                            = 0x10
	WM_COMMAND                          = 0x111
	WM_CONTEXTMENU                      = 0x7b
	WM_CTLCOLOREDIT                     = 0x133
	WM_CTLCOLORSTATIC                   = 0x138
	WM_DESTROY                          = 2
	WM_DPICHANGED                       = 0x2e0
	WM_DRAWITEM                         = 0x2b
	WM_DROPFILES                        = 0x233
	WM_ENTERSIZEMOVE                    = 0x231
	WM_ERASEBKGND                       = 0x14
	WM_EXITSIZEMOVE                     = 0x232
	WM_GETDLGCODE                       = 0x87
	WM_GETMINMAXINFO                    = 0x24
	WM_GETTEXT                          = 0xd
	WM_GETTEXTLENGTH                    = 0xe
	WM_HSCROLL                          = 0x114
	WM_INITMENUPOPUP                    = 0x117
	WM_KEYDOWN                          = 0x100
	WM_KEYUP                            = 0x101
	WM_KILLFOCUS                        = 8
	WM_LBUTTONDBLCLK                    = 0x203
	WM_LBUTTONDOWN                      = 0x201
	WM_LBUTTONUP                        = 0x202
	WM_MBUTTONDOWN                      = 0x207
	WM_MBUTTONUP                        = 0x208
	WM_MEASUREITEM                      = 0x2c
	WM_MOUSEACTIVATE                    = 0x21
	WM_MOUSEMOVE                        = 0x200
	WM_MOUSEWHEEL                       = 0x20a
	WM_NCCALCSIZE                       = 0x83
	WM_NCHITTEST                        = 0x84
	WM_NOTIFY                           = 0x4e
	WM_PAINT                            = 0xf
	WM_PASTE                            = 0x302
	WM_PRINT                            = 0x317
	WM_PRINTCLIENT                      = 0x318
	WM_RBUTTONDBLCLK                    = 0x206
	WM_RBUTTONDOWN                      = 0x204
	WM_RBUTTONUP                        = 0x205
	WM_SETCURSOR                        = 0x20
	WM_SETFOCUS                         = 7
	WM_SETFONT                          = 0x30
	WM_SETICON                          = 0x80
	WM_SETREDRAW                        = 0xb
	WM_SETTEXT                          = 0xc
	WM_SIZE                             = 5
	WM_SYSCOLORCHANGE                   = 0x15
	WM_SYSCOMMAND                       = 0x112
	WM_THEMECHANGED                     = 0x31a
	WM_TIMER                            = 0x113
	WM_UPDATEUISTATE                    = 0x128
	WM_USER                             = 0x400
	WM_VSCROLL                          = 0x115
	WM_WINDOWPOSCHANGED                 = 0x47
)

// Windows.Win32.Web.InternetExplorer
const (
	DISPID_BEFORENAVIGATE2    DISPID = 0xfa
	DISPID_COMMANDSTATECHANGE DISPID = 0x69
	DISPID_DOCUMENTCOMPLETE   DISPID = 0x103
	DISPID_DOWNLOADBEGIN      DISPID = 0x6a
	DISPID_DOWNLOADCOMPLETE   DISPID = 0x68
	DISPID_NAVIGATECOMPLETE2  DISPID = 0xfc
	DISPID_NAVIGATEERROR      DISPID = 0x10f
	DISPID_NEWWINDOW3         DISPID = 0x111
	DISPID_ONQUIT             DISPID = 0xfd
	DISPID_ONSTATUSBAR        DISPID = 0x101
	DISPID_ONTHEATERMODE      DISPID = 0x104
	DISPID_ONTOOLBAR          DISPID = 0xff
	DISPID_ONVISIBLE          DISPID = 0xfe
	DISPID_PROGRESSCHANGE     DISPID = 0x6c
	DISPID_STATUSTEXTCHANGE   DISPID = 0x66
	DISPID_TITLECHANGE        DISPID = 0x71
	DISPID_WINDOWCLOSING      DISPID = 0x107
)
