// Code generated by winmdgen from Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview; DO NOT EDIT.

//go:build windows

package win

import (
	"unsafe"
)

// The functions below do not compile if the layout of a generated
// struct differs from the metadata: an index is out of range or a
// constant overflows uintptr.

var layoutCheck [1]struct{}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BITMAP{})-32]
	_ = layoutCheck[unsafe.Alignof(BITMAP{})-8]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmType)-0]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmWidth)-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmHeight)-8]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmWidthBytes)-12]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmPlanes)-16]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmBitsPixel)-18]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmBits)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BITMAPINFOHEADER{})-40]
	_ = layoutCheck[unsafe.Alignof(BITMAPINFOHEADER{})-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiSize)-0]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiWidth)-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiHeight)-8]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiPlanes)-12]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiBitCount)-14]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiCompression)-16]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiSizeImage)-20]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiXPelsPerMeter)-24]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiYPelsPerMeter)-28]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiClrUsed)-32]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiClrImportant)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BLENDFUNCTION{})-4]
	_ = layoutCheck[unsafe.Alignof(BLENDFUNCTION{})-1]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.BlendOp)-0]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.BlendFlags)-1]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.SourceConstantAlpha)-2]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.AlphaFormat)-3]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BROWSEINFO{})-64]
	_ = layoutCheck[unsafe.Alignof(BROWSEINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.HwndOwner)-0]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.PidlRoot)-8]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.PszDisplayName)-16]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.LpszTitle)-24]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.UlFlags)-32]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.Lpfn)-40]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.LParam)-48]
	_ = layoutCheck[unsafe.Offsetof(BROWSEINFO{}.IImage)-56]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(CIEXYZ{})-12]
	_ = layoutCheck[unsafe.Alignof(CIEXYZ{})-4]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZ{}.CiexyzX)-0]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZ{}.CiexyzY)-4]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZ{}.CiexyzZ)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(CIEXYZTRIPLE{})-36]
	_ = layoutCheck[unsafe.Alignof(CIEXYZTRIPLE{})-4]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZTRIPLE{}.CiexyzRed)-0]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZTRIPLE{}.CiexyzGreen)-12]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZTRIPLE{}.CiexyzBlue)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DIBSECTION{})-104]
	_ = layoutCheck[unsafe.Alignof(DIBSECTION{})-8]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsBm)-0]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsBmih)-32]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsBitfields)-72]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DshSection)-88]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsOffset)-96]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DISPPARAMS{})-24]
	_ = layoutCheck[unsafe.Alignof(DISPPARAMS{})-8]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.Rgvarg)-0]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.RgdispidNamedArgs)-8]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.CArgs)-16]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.CNamedArgs)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DOCHOSTUIINFO{})-32]
	_ = layoutCheck[unsafe.Alignof(DOCHOSTUIINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.DwDoubleClick)-8]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.PchHostCss)-16]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.PchHostNS)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DRAWITEMSTRUCT{})-64]
	_ = layoutCheck[unsafe.Alignof(DRAWITEMSTRUCT{})-8]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.CtlType)-0]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.CtlID)-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemID)-8]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemAction)-12]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemState)-16]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.HwndItem)-24]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.HDC)-32]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.RcItem)-40]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemData)-56]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DRAWTEXTPARAMS{})-20]
	_ = layoutCheck[unsafe.Alignof(DRAWTEXTPARAMS{})-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.ITabLength)-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.ILeftMargin)-8]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.IRightMargin)-12]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.UiLengthDrawn)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DTTOPTS{})-72]
	_ = layoutCheck[unsafe.Alignof(DTTOPTS{})-8]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.DwSize)-0]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.CrText)-8]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.CrBorder)-12]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.CrShadow)-16]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.ITextShadowType)-20]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.PtShadowOffset)-24]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IBorderSize)-32]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IFontPropId)-36]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IColorPropId)-40]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IStateId)-44]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.FApplyOverlay)-48]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IGlowSize)-52]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.PfnDrawTextCallback)-56]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.LParam)-64]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GRADIENT_RECT{})-8]
	_ = layoutCheck[unsafe.Alignof(GRADIENT_RECT{})-4]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_RECT{}.UpperLeft)-0]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_RECT{}.LowerRight)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GRADIENT_TRIANGLE{})-12]
	_ = layoutCheck[unsafe.Alignof(GRADIENT_TRIANGLE{})-4]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_TRIANGLE{}.Vertex1)-0]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_TRIANGLE{}.Vertex2)-4]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_TRIANGLE{}.Vertex3)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GdiplusStartupInput{})-24]
	_ = layoutCheck[unsafe.Alignof(GdiplusStartupInput{})-8]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.GdiplusVersion)-0]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.DebugEventCallback)-8]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.SuppressBackgroundThread)-16]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.SuppressExternalCodecs)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GpBitmap{})-0]
	_ = layoutCheck[unsafe.Alignof(GpBitmap{})-1]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GpImage{})-0]
	_ = layoutCheck[unsafe.Alignof(GpImage{})-1]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(HDHITTESTINFO{})-16]
	_ = layoutCheck[unsafe.Alignof(HDHITTESTINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(HDHITTESTINFO{}.Pt)-0]
	_ = layoutCheck[unsafe.Offsetof(HDHITTESTINFO{}.Flags)-8]
	_ = layoutCheck[unsafe.Offsetof(HDHITTESTINFO{}.IItem)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(HDLAYOUT{})-16]
	_ = layoutCheck[unsafe.Alignof(HDLAYOUT{})-8]
	_ = layoutCheck[unsafe.Offsetof(HDLAYOUT{}.Prc)-0]
	_ = layoutCheck[unsafe.Offsetof(HDLAYOUT{}.Pwpos)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(HIGHCONTRAST{})-16]
	_ = layoutCheck[unsafe.Alignof(HIGHCONTRAST{})-8]
	_ = layoutCheck[unsafe.Offsetof(HIGHCONTRAST{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(HIGHCONTRAST{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(HIGHCONTRAST{}.LpszDefaultScheme)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(ICONINFO{})-32]
	_ = layoutCheck[unsafe.Alignof(ICONINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.FIcon)-0]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.XHotspot)-4]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.YHotspot)-8]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.HbmMask)-16]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.HbmColor)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(INITCOMMONCONTROLSEX{})-8]
	_ = layoutCheck[unsafe.Alignof(INITCOMMONCONTROLSEX{})-4]
	_ = layoutCheck[unsafe.Offsetof(INITCOMMONCONTROLSEX{}.DwSize)-0]
	_ = layoutCheck[unsafe.Offsetof(INITCOMMONCONTROLSEX{}.DwICC)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LITEM{})-4280]
	_ = layoutCheck[unsafe.Alignof(LITEM{})-4]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.Mask)-0]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.ILink)-4]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.State)-8]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.StateMask)-12]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.SzID)-16]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.SzUrl)-112]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LOGBRUSH{})-16]
	_ = layoutCheck[unsafe.Alignof(LOGBRUSH{})-8]
	_ = layoutCheck[unsafe.Offsetof(LOGBRUSH{}.LbStyle)-0]
	_ = layoutCheck[unsafe.Offsetof(LOGBRUSH{}.LbColor)-4]
	_ = layoutCheck[unsafe.Offsetof(LOGBRUSH{}.LbHatch)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LOGFONT{})-92]
	_ = layoutCheck[unsafe.Alignof(LOGFONT{})-4]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfHeight)-0]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfWidth)-4]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfEscapement)-8]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfOrientation)-12]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfWeight)-16]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfItalic)-20]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfUnderline)-21]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfStrikeOut)-22]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfCharSet)-23]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfOutPrecision)-24]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfClipPrecision)-25]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfQuality)-26]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfPitchAndFamily)-27]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfFaceName)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LVHITTESTINFO{})-24]
	_ = layoutCheck[unsafe.Alignof(LVHITTESTINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.Pt)-0]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.Flags)-8]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.IItem)-12]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.ISubItem)-16]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.IGroup)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MEASUREITEMSTRUCT{})-32]
	_ = layoutCheck[unsafe.Alignof(MEASUREITEMSTRUCT{})-8]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.CtlType)-0]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.CtlID)-4]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemID)-8]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemWidth)-12]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemHeight)-16]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemData)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MENUINFO{})-40]
	_ = layoutCheck[unsafe.Alignof(MENUINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.FMask)-4]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.DwStyle)-8]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.CyMax)-12]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.HbrBack)-16]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.DwContextHelpID)-24]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.DwMenuData)-32]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MENUITEMINFO{})-80]
	_ = layoutCheck[unsafe.Alignof(MENUITEMINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.FMask)-4]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.FType)-8]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.FState)-12]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.WID)-16]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HSubMenu)-24]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HbmpChecked)-32]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HbmpUnchecked)-40]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.DwItemData)-48]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.DwTypeData)-56]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.Cch)-64]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HbmpItem)-72]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MINMAXINFO{})-40]
	_ = layoutCheck[unsafe.Alignof(MINMAXINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtReserved)-0]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMaxSize)-8]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMaxPosition)-16]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMinTrackSize)-24]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMaxTrackSize)-32]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MONITORINFO{})-40]
	_ = layoutCheck[unsafe.Alignof(MONITORINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.RcMonitor)-4]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.RcWork)-20]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.DwFlags)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MSG{})-48]
	_ = layoutCheck[unsafe.Alignof(MSG{})-8]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.HWnd)-0]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.Message)-8]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.WParam)-16]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.LParam)-24]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.Time)-32]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.Pt)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMBCDROPDOWN{})-40]
	_ = layoutCheck[unsafe.Alignof(NMBCDROPDOWN{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMBCDROPDOWN{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMBCDROPDOWN{}.RcButton)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMCUSTOMDRAW{})-80]
	_ = layoutCheck[unsafe.Alignof(NMCUSTOMDRAW{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.DwDrawStage)-24]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.Hdc)-32]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.Rc)-40]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.DwItemSpec)-56]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.UItemState)-64]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.LItemlParam)-72]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMHDR{})-24]
	_ = layoutCheck[unsafe.Alignof(NMHDR{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMHDR{}.HwndFrom)-0]
	_ = layoutCheck[unsafe.Offsetof(NMHDR{}.IdFrom)-8]
	_ = layoutCheck[unsafe.Offsetof(NMHDR{}.Code)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMITEMACTIVATE{})-72]
	_ = layoutCheck[unsafe.Alignof(NMITEMACTIVATE{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.IItem)-24]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.ISubItem)-28]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UNewState)-32]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UOldState)-36]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UChanged)-40]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.PtAction)-44]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.LParam)-56]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UKeyFlags)-64]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLINK{})-4304]
	_ = layoutCheck[unsafe.Alignof(NMLINK{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMLINK{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLINK{}.Item)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLISTVIEW{})-64]
	_ = layoutCheck[unsafe.Alignof(NMLISTVIEW{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.IItem)-24]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.ISubItem)-28]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.UNewState)-32]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.UOldState)-36]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.UChanged)-40]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.PtAction)-44]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.LParam)-56]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLVCUSTOMDRAW{})-136]
	_ = layoutCheck[unsafe.Alignof(NMLVCUSTOMDRAW{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.Nmcd)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ClrText)-80]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ClrTextBk)-84]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ISubItem)-88]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.DwItemType)-92]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ClrFace)-96]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IIconEffect)-100]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IIconPhase)-104]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IPartId)-108]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IStateId)-112]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.RcText)-116]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.UAlign)-132]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLVSCROLL{})-32]
	_ = layoutCheck[unsafe.Alignof(NMLVSCROLL{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMLVSCROLL{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLVSCROLL{}.Dx)-24]
	_ = layoutCheck[unsafe.Offsetof(NMLVSCROLL{}.Dy)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMMOUSE{})-56]
	_ = layoutCheck[unsafe.Alignof(NMMOUSE{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.DwItemSpec)-24]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.DwItemData)-32]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.Pt)-40]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.DwHitInfo)-48]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMTOOLBAR{})-96]
	_ = layoutCheck[unsafe.Alignof(NMTOOLBAR{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.IItem)-24]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.TbButton)-32]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.CchText)-64]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.PszText)-72]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.RcButton)-80]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMTREEVIEW{})-152]
	_ = layoutCheck[unsafe.Alignof(NMTREEVIEW{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.Action)-24]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.ItemOld)-32]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.ItemNew)-88]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.PtDrag)-144]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMTVDISPINFO{})-80]
	_ = layoutCheck[unsafe.Alignof(NMTVDISPINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMTVDISPINFO{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMTVDISPINFO{}.Item)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMUPDOWN{})-32]
	_ = layoutCheck[unsafe.Alignof(NMUPDOWN{})-8]
	_ = layoutCheck[unsafe.Offsetof(NMUPDOWN{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMUPDOWN{}.IPos)-24]
	_ = layoutCheck[unsafe.Offsetof(NMUPDOWN{}.IDelta)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(OLEINPLACEFRAMEINFO{})-32]
	_ = layoutCheck[unsafe.Alignof(OLEINPLACEFRAMEINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.Cb)-0]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.FMDIApp)-4]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.HwndFrame)-8]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.Haccel)-16]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.CAccelEntries)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(PAINTSTRUCT{})-72]
	_ = layoutCheck[unsafe.Alignof(PAINTSTRUCT{})-8]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.Hdc)-0]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.FErase)-8]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.RcPaint)-12]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.FRestore)-28]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.FIncUpdate)-32]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.RgbReserved)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(POINT{})-8]
	_ = layoutCheck[unsafe.Alignof(POINT{})-4]
	_ = layoutCheck[unsafe.Offsetof(POINT{}.X)-0]
	_ = layoutCheck[unsafe.Offsetof(POINT{}.Y)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(RECT{})-16]
	_ = layoutCheck[unsafe.Alignof(RECT{})-4]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Left)-0]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Top)-4]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Right)-8]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Bottom)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(SCROLLINFO{})-28]
	_ = layoutCheck[unsafe.Alignof(SCROLLINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.FMask)-4]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NMin)-8]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NMax)-12]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NPage)-16]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NPos)-20]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NTrackPos)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(SIZE{})-8]
	_ = layoutCheck[unsafe.Alignof(SIZE{})-4]
	_ = layoutCheck[unsafe.Offsetof(SIZE{}.CX)-0]
	_ = layoutCheck[unsafe.Offsetof(SIZE{}.CY)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(SYSTEMTIME{})-16]
	_ = layoutCheck[unsafe.Alignof(SYSTEMTIME{})-2]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WYear)-0]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WMonth)-2]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WDayOfWeek)-4]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WDay)-6]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WHour)-8]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WMinute)-10]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WSecond)-12]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WMilliseconds)-14]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TBBUTTONINFO{})-48]
	_ = layoutCheck[unsafe.Alignof(TBBUTTONINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.DwMask)-4]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.IdCommand)-8]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.IImage)-12]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.FsState)-16]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.FsStyle)-17]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.Cx)-18]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.LParam)-24]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.PszText)-32]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.CchText)-40]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TCITEM{})-40]
	_ = layoutCheck[unsafe.Alignof(TCITEM{})-8]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.Mask)-0]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.DwState)-4]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.DwStateMask)-8]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.PszText)-16]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.CchTextMax)-24]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.IImage)-28]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.LParam)-32]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TEXTMETRIC{})-60]
	_ = layoutCheck[unsafe.Alignof(TEXTMETRIC{})-4]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmHeight)-0]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmAscent)-4]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDescent)-8]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmInternalLeading)-12]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmExternalLeading)-16]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmAveCharWidth)-20]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmMaxCharWidth)-24]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmWeight)-28]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmOverhang)-32]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDigitizedAspectX)-36]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDigitizedAspectY)-40]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmFirstChar)-44]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmLastChar)-46]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDefaultChar)-48]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmBreakChar)-50]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmItalic)-52]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmUnderlined)-53]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmStruckOut)-54]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmPitchAndFamily)-55]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmCharSet)-56]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TRACKMOUSEEVENT{})-24]
	_ = layoutCheck[unsafe.Alignof(TRACKMOUSEEVENT{})-8]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.HwndTrack)-8]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.DwHoverTime)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TRIVERTEX{})-16]
	_ = layoutCheck[unsafe.Alignof(TRIVERTEX{})-4]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.X)-0]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Y)-4]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Red)-8]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Green)-10]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Blue)-12]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Alpha)-14]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TTGETTITLE{})-24]
	_ = layoutCheck[unsafe.Alignof(TTGETTITLE{})-8]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.DwSize)-0]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.UTitleBitmap)-4]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.Cch)-8]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.PszTitle)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TVHITTESTINFO{})-24]
	_ = layoutCheck[unsafe.Alignof(TVHITTESTINFO{})-8]
	_ = layoutCheck[unsafe.Offsetof(TVHITTESTINFO{}.Pt)-0]
	_ = layoutCheck[unsafe.Offsetof(TVHITTESTINFO{}.Flags)-8]
	_ = layoutCheck[unsafe.Offsetof(TVHITTESTINFO{}.HItem)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TVITEM{})-56]
	_ = layoutCheck[unsafe.Alignof(TVITEM{})-8]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.Mask)-0]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.HItem)-8]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.State)-16]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.StateMask)-20]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.PszText)-24]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.CchTextMax)-32]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.IImage)-36]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.ISelectedImage)-40]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.CChildren)-44]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.LParam)-48]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(WINDOWPLACEMENT{})-44]
	_ = layoutCheck[unsafe.Alignof(WINDOWPLACEMENT{})-4]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.Length)-0]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.Flags)-4]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.ShowCmd)-8]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.PtMinPosition)-12]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.PtMaxPosition)-20]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.RcNormalPosition)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(WINDOWPOS{})-40]
	_ = layoutCheck[unsafe.Alignof(WINDOWPOS{})-8]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Hwnd)-0]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.HwndInsertAfter)-8]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.X)-16]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Y)-20]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Cx)-24]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Cy)-28]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Flags)-32]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(WNDCLASSEX{})-80]
	_ = layoutCheck[unsafe.Alignof(WNDCLASSEX{})-8]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.Style)-4]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.LpfnWndProc)-8]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.CbClsExtra)-16]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.CbWndExtra)-20]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HInstance)-24]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HIcon)-32]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HCursor)-40]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HbrBackground)-48]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.LpszMenuName)-56]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.LpszClassName)-64]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HIconSm)-72]
}
