// Code generated by winmdgen from Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview; DO NOT EDIT.

//go:build windows

package win

import (
	"unsafe"
)

// The functions below do not compile if the layout of a generated
// struct differs from the metadata: an index is out of range or a
// constant overflows uintptr.

var layoutCheck [1]struct{}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BITMAP{})-24]
	_ = layoutCheck[unsafe.Alignof(BITMAP{})-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmType)-0]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmWidth)-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmHeight)-8]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmWidthBytes)-12]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmPlanes)-16]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmBitsPixel)-18]
	_ = layoutCheck[unsafe.Offsetof(BITMAP{}.BmBits)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BITMAPINFOHEADER{})-40]
	_ = layoutCheck[unsafe.Alignof(BITMAPINFOHEADER{})-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiSize)-0]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiWidth)-4]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiHeight)-8]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiPlanes)-12]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiBitCount)-14]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiCompression)-16]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiSizeImage)-20]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiXPelsPerMeter)-24]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiYPelsPerMeter)-28]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiClrUsed)-32]
	_ = layoutCheck[unsafe.Offsetof(BITMAPINFOHEADER{}.BiClrImportant)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(BLENDFUNCTION{})-4]
	_ = layoutCheck[unsafe.Alignof(BLENDFUNCTION{})-1]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.BlendOp)-0]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.BlendFlags)-1]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.SourceConstantAlpha)-2]
	_ = layoutCheck[unsafe.Offsetof(BLENDFUNCTION{}.AlphaFormat)-3]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(CIEXYZ{})-12]
	_ = layoutCheck[unsafe.Alignof(CIEXYZ{})-4]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZ{}.CiexyzX)-0]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZ{}.CiexyzY)-4]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZ{}.CiexyzZ)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(CIEXYZTRIPLE{})-36]
	_ = layoutCheck[unsafe.Alignof(CIEXYZTRIPLE{})-4]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZTRIPLE{}.CiexyzRed)-0]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZTRIPLE{}.CiexyzGreen)-12]
	_ = layoutCheck[unsafe.Offsetof(CIEXYZTRIPLE{}.CiexyzBlue)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DIBSECTION{})-84]
	_ = layoutCheck[unsafe.Alignof(DIBSECTION{})-4]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsBm)-0]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsBmih)-24]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsBitfields)-64]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DshSection)-76]
	_ = layoutCheck[unsafe.Offsetof(DIBSECTION{}.DsOffset)-80]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DISPPARAMS{})-16]
	_ = layoutCheck[unsafe.Alignof(DISPPARAMS{})-4]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.Rgvarg)-0]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.RgdispidNamedArgs)-4]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.CArgs)-8]
	_ = layoutCheck[unsafe.Offsetof(DISPPARAMS{}.CNamedArgs)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DOCHOSTUIINFO{})-20]
	_ = layoutCheck[unsafe.Alignof(DOCHOSTUIINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.DwDoubleClick)-8]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.PchHostCss)-12]
	_ = layoutCheck[unsafe.Offsetof(DOCHOSTUIINFO{}.PchHostNS)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DRAWITEMSTRUCT{})-48]
	_ = layoutCheck[unsafe.Alignof(DRAWITEMSTRUCT{})-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.CtlType)-0]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.CtlID)-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemID)-8]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemAction)-12]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemState)-16]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.HwndItem)-20]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.HDC)-24]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.RcItem)-28]
	_ = layoutCheck[unsafe.Offsetof(DRAWITEMSTRUCT{}.ItemData)-44]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DRAWTEXTPARAMS{})-20]
	_ = layoutCheck[unsafe.Alignof(DRAWTEXTPARAMS{})-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.ITabLength)-4]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.ILeftMargin)-8]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.IRightMargin)-12]
	_ = layoutCheck[unsafe.Offsetof(DRAWTEXTPARAMS{}.UiLengthDrawn)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(DTTOPTS{})-64]
	_ = layoutCheck[unsafe.Alignof(DTTOPTS{})-4]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.DwSize)-0]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.CrText)-8]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.CrBorder)-12]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.CrShadow)-16]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.ITextShadowType)-20]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.PtShadowOffset)-24]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IBorderSize)-32]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IFontPropId)-36]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IColorPropId)-40]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IStateId)-44]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.FApplyOverlay)-48]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.IGlowSize)-52]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.PfnDrawTextCallback)-56]
	_ = layoutCheck[unsafe.Offsetof(DTTOPTS{}.LParam)-60]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GRADIENT_RECT{})-8]
	_ = layoutCheck[unsafe.Alignof(GRADIENT_RECT{})-4]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_RECT{}.UpperLeft)-0]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_RECT{}.LowerRight)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GRADIENT_TRIANGLE{})-12]
	_ = layoutCheck[unsafe.Alignof(GRADIENT_TRIANGLE{})-4]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_TRIANGLE{}.Vertex1)-0]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_TRIANGLE{}.Vertex2)-4]
	_ = layoutCheck[unsafe.Offsetof(GRADIENT_TRIANGLE{}.Vertex3)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GdiplusStartupInput{})-16]
	_ = layoutCheck[unsafe.Alignof(GdiplusStartupInput{})-4]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.GdiplusVersion)-0]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.DebugEventCallback)-4]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.SuppressBackgroundThread)-8]
	_ = layoutCheck[unsafe.Offsetof(GdiplusStartupInput{}.SuppressExternalCodecs)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GpBitmap{})-0]
	_ = layoutCheck[unsafe.Alignof(GpBitmap{})-1]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(GpImage{})-0]
	_ = layoutCheck[unsafe.Alignof(GpImage{})-1]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(HDHITTESTINFO{})-16]
	_ = layoutCheck[unsafe.Alignof(HDHITTESTINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(HDHITTESTINFO{}.Pt)-0]
	_ = layoutCheck[unsafe.Offsetof(HDHITTESTINFO{}.Flags)-8]
	_ = layoutCheck[unsafe.Offsetof(HDHITTESTINFO{}.IItem)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(HDLAYOUT{})-8]
	_ = layoutCheck[unsafe.Alignof(HDLAYOUT{})-4]
	_ = layoutCheck[unsafe.Offsetof(HDLAYOUT{}.Prc)-0]
	_ = layoutCheck[unsafe.Offsetof(HDLAYOUT{}.Pwpos)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(HIGHCONTRAST{})-12]
	_ = layoutCheck[unsafe.Alignof(HIGHCONTRAST{})-4]
	_ = layoutCheck[unsafe.Offsetof(HIGHCONTRAST{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(HIGHCONTRAST{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(HIGHCONTRAST{}.LpszDefaultScheme)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(ICONINFO{})-20]
	_ = layoutCheck[unsafe.Alignof(ICONINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.FIcon)-0]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.XHotspot)-4]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.YHotspot)-8]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.HbmMask)-12]
	_ = layoutCheck[unsafe.Offsetof(ICONINFO{}.HbmColor)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(INITCOMMONCONTROLSEX{})-8]
	_ = layoutCheck[unsafe.Alignof(INITCOMMONCONTROLSEX{})-4]
	_ = layoutCheck[unsafe.Offsetof(INITCOMMONCONTROLSEX{}.DwSize)-0]
	_ = layoutCheck[unsafe.Offsetof(INITCOMMONCONTROLSEX{}.DwICC)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LITEM{})-4280]
	_ = layoutCheck[unsafe.Alignof(LITEM{})-4]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.Mask)-0]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.ILink)-4]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.State)-8]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.StateMask)-12]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.SzID)-16]
	_ = layoutCheck[unsafe.Offsetof(LITEM{}.SzUrl)-112]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LOGBRUSH{})-12]
	_ = layoutCheck[unsafe.Alignof(LOGBRUSH{})-4]
	_ = layoutCheck[unsafe.Offsetof(LOGBRUSH{}.LbStyle)-0]
	_ = layoutCheck[unsafe.Offsetof(LOGBRUSH{}.LbColor)-4]
	_ = layoutCheck[unsafe.Offsetof(LOGBRUSH{}.LbHatch)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LOGFONT{})-92]
	_ = layoutCheck[unsafe.Alignof(LOGFONT{})-4]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfHeight)-0]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfWidth)-4]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfEscapement)-8]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfOrientation)-12]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfWeight)-16]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfItalic)-20]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfUnderline)-21]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfStrikeOut)-22]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfCharSet)-23]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfOutPrecision)-24]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfClipPrecision)-25]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfQuality)-26]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfPitchAndFamily)-27]
	_ = layoutCheck[unsafe.Offsetof(LOGFONT{}.LfFaceName)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(LVHITTESTINFO{})-24]
	_ = layoutCheck[unsafe.Alignof(LVHITTESTINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.Pt)-0]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.Flags)-8]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.IItem)-12]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.ISubItem)-16]
	_ = layoutCheck[unsafe.Offsetof(LVHITTESTINFO{}.IGroup)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MEASUREITEMSTRUCT{})-24]
	_ = layoutCheck[unsafe.Alignof(MEASUREITEMSTRUCT{})-4]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.CtlType)-0]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.CtlID)-4]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemID)-8]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemWidth)-12]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemHeight)-16]
	_ = layoutCheck[unsafe.Offsetof(MEASUREITEMSTRUCT{}.ItemData)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MENUINFO{})-28]
	_ = layoutCheck[unsafe.Alignof(MENUINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.FMask)-4]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.DwStyle)-8]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.CyMax)-12]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.HbrBack)-16]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.DwContextHelpID)-20]
	_ = layoutCheck[unsafe.Offsetof(MENUINFO{}.DwMenuData)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MENUITEMINFO{})-48]
	_ = layoutCheck[unsafe.Alignof(MENUITEMINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.FMask)-4]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.FType)-8]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.FState)-12]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.WID)-16]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HSubMenu)-20]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HbmpChecked)-24]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HbmpUnchecked)-28]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.DwItemData)-32]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.DwTypeData)-36]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.Cch)-40]
	_ = layoutCheck[unsafe.Offsetof(MENUITEMINFO{}.HbmpItem)-44]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MINMAXINFO{})-40]
	_ = layoutCheck[unsafe.Alignof(MINMAXINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtReserved)-0]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMaxSize)-8]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMaxPosition)-16]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMinTrackSize)-24]
	_ = layoutCheck[unsafe.Offsetof(MINMAXINFO{}.PtMaxTrackSize)-32]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MONITORINFO{})-40]
	_ = layoutCheck[unsafe.Alignof(MONITORINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.RcMonitor)-4]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.RcWork)-20]
	_ = layoutCheck[unsafe.Offsetof(MONITORINFO{}.DwFlags)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(MSG{})-28]
	_ = layoutCheck[unsafe.Alignof(MSG{})-4]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.HWnd)-0]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.Message)-4]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.WParam)-8]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.LParam)-12]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.Time)-16]
	_ = layoutCheck[unsafe.Offsetof(MSG{}.Pt)-20]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMBCDROPDOWN{})-28]
	_ = layoutCheck[unsafe.Alignof(NMBCDROPDOWN{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMBCDROPDOWN{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMBCDROPDOWN{}.RcButton)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMCUSTOMDRAW{})-48]
	_ = layoutCheck[unsafe.Alignof(NMCUSTOMDRAW{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.DwDrawStage)-12]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.Hdc)-16]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.Rc)-20]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.DwItemSpec)-36]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.UItemState)-40]
	_ = layoutCheck[unsafe.Offsetof(NMCUSTOMDRAW{}.LItemlParam)-44]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMHDR{})-12]
	_ = layoutCheck[unsafe.Alignof(NMHDR{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMHDR{}.HwndFrom)-0]
	_ = layoutCheck[unsafe.Offsetof(NMHDR{}.IdFrom)-4]
	_ = layoutCheck[unsafe.Offsetof(NMHDR{}.Code)-8]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMITEMACTIVATE{})-48]
	_ = layoutCheck[unsafe.Alignof(NMITEMACTIVATE{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.IItem)-12]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.ISubItem)-16]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UNewState)-20]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UOldState)-24]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UChanged)-28]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.PtAction)-32]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.LParam)-40]
	_ = layoutCheck[unsafe.Offsetof(NMITEMACTIVATE{}.UKeyFlags)-44]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLINK{})-4292]
	_ = layoutCheck[unsafe.Alignof(NMLINK{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMLINK{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLINK{}.Item)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLISTVIEW{})-44]
	_ = layoutCheck[unsafe.Alignof(NMLISTVIEW{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.IItem)-12]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.ISubItem)-16]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.UNewState)-20]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.UOldState)-24]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.UChanged)-28]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.PtAction)-32]
	_ = layoutCheck[unsafe.Offsetof(NMLISTVIEW{}.LParam)-40]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLVCUSTOMDRAW{})-104]
	_ = layoutCheck[unsafe.Alignof(NMLVCUSTOMDRAW{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.Nmcd)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ClrText)-48]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ClrTextBk)-52]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ISubItem)-56]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.DwItemType)-60]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.ClrFace)-64]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IIconEffect)-68]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IIconPhase)-72]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IPartId)-76]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.IStateId)-80]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.RcText)-84]
	_ = layoutCheck[unsafe.Offsetof(NMLVCUSTOMDRAW{}.UAlign)-100]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMLVSCROLL{})-20]
	_ = layoutCheck[unsafe.Alignof(NMLVSCROLL{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMLVSCROLL{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMLVSCROLL{}.Dx)-12]
	_ = layoutCheck[unsafe.Offsetof(NMLVSCROLL{}.Dy)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMMOUSE{})-32]
	_ = layoutCheck[unsafe.Alignof(NMMOUSE{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.DwItemSpec)-12]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.DwItemData)-16]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.Pt)-20]
	_ = layoutCheck[unsafe.Offsetof(NMMOUSE{}.DwHitInfo)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMTOOLBAR{})-60]
	_ = layoutCheck[unsafe.Alignof(NMTOOLBAR{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.IItem)-12]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.TbButton)-16]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.CchText)-36]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.PszText)-40]
	_ = layoutCheck[unsafe.Offsetof(NMTOOLBAR{}.RcButton)-44]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMTREEVIEW{})-104]
	_ = layoutCheck[unsafe.Alignof(NMTREEVIEW{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.Action)-12]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.ItemOld)-16]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.ItemNew)-56]
	_ = layoutCheck[unsafe.Offsetof(NMTREEVIEW{}.PtDrag)-96]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMTVDISPINFO{})-52]
	_ = layoutCheck[unsafe.Alignof(NMTVDISPINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMTVDISPINFO{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMTVDISPINFO{}.Item)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(NMUPDOWN{})-20]
	_ = layoutCheck[unsafe.Alignof(NMUPDOWN{})-4]
	_ = layoutCheck[unsafe.Offsetof(NMUPDOWN{}.Hdr)-0]
	_ = layoutCheck[unsafe.Offsetof(NMUPDOWN{}.IPos)-12]
	_ = layoutCheck[unsafe.Offsetof(NMUPDOWN{}.IDelta)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(OLEINPLACEFRAMEINFO{})-20]
	_ = layoutCheck[unsafe.Alignof(OLEINPLACEFRAMEINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.Cb)-0]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.FMDIApp)-4]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.HwndFrame)-8]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.Haccel)-12]
	_ = layoutCheck[unsafe.Offsetof(OLEINPLACEFRAMEINFO{}.CAccelEntries)-16]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(PAINTSTRUCT{})-64]
	_ = layoutCheck[unsafe.Alignof(PAINTSTRUCT{})-4]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.Hdc)-0]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.FErase)-4]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.RcPaint)-8]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.FRestore)-24]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.FIncUpdate)-28]
	_ = layoutCheck[unsafe.Offsetof(PAINTSTRUCT{}.RgbReserved)-32]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(POINT{})-8]
	_ = layoutCheck[unsafe.Alignof(POINT{})-4]
	_ = layoutCheck[unsafe.Offsetof(POINT{}.X)-0]
	_ = layoutCheck[unsafe.Offsetof(POINT{}.Y)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(RECT{})-16]
	_ = layoutCheck[unsafe.Alignof(RECT{})-4]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Left)-0]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Top)-4]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Right)-8]
	_ = layoutCheck[unsafe.Offsetof(RECT{}.Bottom)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(SCROLLINFO{})-28]
	_ = layoutCheck[unsafe.Alignof(SCROLLINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.FMask)-4]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NMin)-8]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NMax)-12]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NPage)-16]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NPos)-20]
	_ = layoutCheck[unsafe.Offsetof(SCROLLINFO{}.NTrackPos)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(SIZE{})-8]
	_ = layoutCheck[unsafe.Alignof(SIZE{})-4]
	_ = layoutCheck[unsafe.Offsetof(SIZE{}.CX)-0]
	_ = layoutCheck[unsafe.Offsetof(SIZE{}.CY)-4]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(SYSTEMTIME{})-16]
	_ = layoutCheck[unsafe.Alignof(SYSTEMTIME{})-2]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WYear)-0]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WMonth)-2]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WDayOfWeek)-4]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WDay)-6]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WHour)-8]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WMinute)-10]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WSecond)-12]
	_ = layoutCheck[unsafe.Offsetof(SYSTEMTIME{}.WMilliseconds)-14]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TBBUTTONINFO{})-32]
	_ = layoutCheck[unsafe.Alignof(TBBUTTONINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.DwMask)-4]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.IdCommand)-8]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.IImage)-12]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.FsState)-16]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.FsStyle)-17]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.Cx)-18]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.LParam)-20]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.PszText)-24]
	_ = layoutCheck[unsafe.Offsetof(TBBUTTONINFO{}.CchText)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TCITEM{})-28]
	_ = layoutCheck[unsafe.Alignof(TCITEM{})-4]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.Mask)-0]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.DwState)-4]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.DwStateMask)-8]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.PszText)-12]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.CchTextMax)-16]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.IImage)-20]
	_ = layoutCheck[unsafe.Offsetof(TCITEM{}.LParam)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TEXTMETRIC{})-60]
	_ = layoutCheck[unsafe.Alignof(TEXTMETRIC{})-4]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmHeight)-0]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmAscent)-4]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDescent)-8]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmInternalLeading)-12]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmExternalLeading)-16]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmAveCharWidth)-20]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmMaxCharWidth)-24]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmWeight)-28]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmOverhang)-32]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDigitizedAspectX)-36]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDigitizedAspectY)-40]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmFirstChar)-44]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmLastChar)-46]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmDefaultChar)-48]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmBreakChar)-50]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmItalic)-52]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmUnderlined)-53]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmStruckOut)-54]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmPitchAndFamily)-55]
	_ = layoutCheck[unsafe.Offsetof(TEXTMETRIC{}.TmCharSet)-56]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TRACKMOUSEEVENT{})-16]
	_ = layoutCheck[unsafe.Alignof(TRACKMOUSEEVENT{})-4]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.DwFlags)-4]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.HwndTrack)-8]
	_ = layoutCheck[unsafe.Offsetof(TRACKMOUSEEVENT{}.DwHoverTime)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TRIVERTEX{})-16]
	_ = layoutCheck[unsafe.Alignof(TRIVERTEX{})-4]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.X)-0]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Y)-4]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Red)-8]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Green)-10]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Blue)-12]
	_ = layoutCheck[unsafe.Offsetof(TRIVERTEX{}.Alpha)-14]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TTGETTITLE{})-16]
	_ = layoutCheck[unsafe.Alignof(TTGETTITLE{})-4]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.DwSize)-0]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.UTitleBitmap)-4]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.Cch)-8]
	_ = layoutCheck[unsafe.Offsetof(TTGETTITLE{}.PszTitle)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TVHITTESTINFO{})-16]
	_ = layoutCheck[unsafe.Alignof(TVHITTESTINFO{})-4]
	_ = layoutCheck[unsafe.Offsetof(TVHITTESTINFO{}.Pt)-0]
	_ = layoutCheck[unsafe.Offsetof(TVHITTESTINFO{}.Flags)-8]
	_ = layoutCheck[unsafe.Offsetof(TVHITTESTINFO{}.HItem)-12]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(TVITEM{})-40]
	_ = layoutCheck[unsafe.Alignof(TVITEM{})-4]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.Mask)-0]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.HItem)-4]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.State)-8]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.StateMask)-12]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.PszText)-16]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.CchTextMax)-20]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.IImage)-24]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.ISelectedImage)-28]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.CChildren)-32]
	_ = layoutCheck[unsafe.Offsetof(TVITEM{}.LParam)-36]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(WINDOWPLACEMENT{})-44]
	_ = layoutCheck[unsafe.Alignof(WINDOWPLACEMENT{})-4]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.Length)-0]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.Flags)-4]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.ShowCmd)-8]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.PtMinPosition)-12]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.PtMaxPosition)-20]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPLACEMENT{}.RcNormalPosition)-28]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(WINDOWPOS{})-28]
	_ = layoutCheck[unsafe.Alignof(WINDOWPOS{})-4]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Hwnd)-0]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.HwndInsertAfter)-4]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.X)-8]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Y)-12]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Cx)-16]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Cy)-20]
	_ = layoutCheck[unsafe.Offsetof(WINDOWPOS{}.Flags)-24]
}

func _() {
	_ = layoutCheck[unsafe.Sizeof(WNDCLASSEX{})-48]
	_ = layoutCheck[unsafe.Alignof(WNDCLASSEX{})-4]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.CbSize)-0]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.Style)-4]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.LpfnWndProc)-8]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.CbClsExtra)-12]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.CbWndExtra)-16]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HInstance)-20]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HIcon)-24]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HCursor)-28]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HbrBackground)-32]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.LpszMenuName)-36]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.LpszClassName)-40]
	_ = layoutCheck[unsafe.Offsetof(WNDCLASSEX{}.HIconSm)-44]
}
