// Code generated by winmdgen from Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview; DO NOT EDIT.

//go:build windows

package win

var (
	procGetWindowLongPtr = libuser32.NewProc("GetWindowLongW")
	procSetWindowLongPtr = libuser32.NewProc("SetWindowLongW")
)
