// Code generated by winmdgen from Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview; DO NOT EDIT.

//go:build windows

package win

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var (
	libadvapi32 = windows.NewLazySystemDLL("advapi32.dll")
	libcomctl32 = windows.NewLazySystemDLL("comctl32.dll")
	libcomdlg32 = windows.NewLazySystemDLL("comdlg32.dll")
	libgdi32    = windows.NewLazySystemDLL("gdi32.dll")
	libgdiplus  = windows.NewLazySystemDLL("gdiplus.dll")
	libkernel32 = windows.NewLazySystemDLL("kernel32.dll")
	libmsimg32  = windows.NewLazySystemDLL("msimg32.dll")
	libole32    = windows.NewLazySystemDLL("ole32.dll")
	liboleaut32 = windows.NewLazySystemDLL("oleaut32.dll")
	libshell32  = windows.NewLazySystemDLL("shell32.dll")
	libuser32   = windows.NewLazySystemDLL("user32.dll")
	libuxtheme  = windows.NewLazySystemDLL("uxtheme.dll")

	procAddFontMemResourceEx        = libgdi32.NewProc("AddFontMemResourceEx")
	procAlphaBlend                  = libmsimg32.NewProc("AlphaBlend")
	procBeginDeferWindowPos         = libuser32.NewProc("BeginDeferWindowPos")
	procBeginPaint                  = libuser32.NewProc("BeginPaint")
	procBitBlt                      = libgdi32.NewProc("BitBlt")
	procCallWindowProcW             = libuser32.NewProc("CallWindowProcW")
	procChangeWindowMessageFilterEx = libuser32.NewProc("ChangeWindowMessageFilterEx")
	procCheckMenuRadioItem          = libuser32.NewProc("CheckMenuRadioItem")
	procClientToScreen              = libuser32.NewProc("ClientToScreen")
	procCloseClipboard              = libuser32.NewProc("CloseClipboard")
	procCloseEnhMetaFile            = libgdi32.NewProc("CloseEnhMetaFile")
	procCloseThemeData              = libuxtheme.NewProc("CloseThemeData")
	procCoCreateInstance            = libole32.NewProc("CoCreateInstance")
	procCoGetClassObject            = libole32.NewProc("CoGetClassObject")
	procCoTaskMemFree               = libole32.NewProc("CoTaskMemFree")
	procCombineRgn                  = libgdi32.NewProc("CombineRgn")
	procCommDlgExtendedError        = libcomdlg32.NewProc("CommDlgExtendedError")
	procCopyEnhMetaFileW            = libgdi32.NewProc("CopyEnhMetaFileW")
	procCreateBitmap                = libgdi32.NewProc("CreateBitmap")
	procCreateBrushIndirect         = libgdi32.NewProc("CreateBrushIndirect")
	procCreateCompatibleBitmap      = libgdi32.NewProc("CreateCompatibleBitmap")
	procCreateCompatibleDC          = libgdi32.NewProc("CreateCompatibleDC")
	procCreateDIBSection            = libgdi32.NewProc("CreateDIBSection")
	procCreateEnhMetaFileW          = libgdi32.NewProc("CreateEnhMetaFileW")
	procCreateFontIndirectW         = libgdi32.NewProc("CreateFontIndirectW")
	procCreateIconIndirect          = libuser32.NewProc("CreateIconIndirect")
	procCreateMenu                  = libuser32.NewProc("CreateMenu")
	procCreatePatternBrush          = libgdi32.NewProc("CreatePatternBrush")
	procCreatePopupMenu             = libuser32.NewProc("CreatePopupMenu")
	procCreateRectRgn               = libgdi32.NewProc("CreateRectRgn")
	procCreateWindowExW             = libuser32.NewProc("CreateWindowExW")
	procDefWindowProcW              = libuser32.NewProc("DefWindowProcW")
	procDeferWindowPos              = libuser32.NewProc("DeferWindowPos")
	procDeleteDC                    = libgdi32.NewProc("DeleteDC")
	procDeleteEnhMetaFile           = libgdi32.NewProc("DeleteEnhMetaFile")
	procDeleteObject                = libgdi32.NewProc("DeleteObject")
	procDestroyIcon                 = libuser32.NewProc("DestroyIcon")
	procDestroyMenu                 = libuser32.NewProc("DestroyMenu")
	procDestroyWindow               = libuser32.NewProc("DestroyWindow")
	procDispatchMessageW            = libuser32.NewProc("DispatchMessageW")
	procDragQueryFileW              = libshell32.NewProc("DragQueryFileW")
	procDrawIconEx                  = libuser32.NewProc("DrawIconEx")
	procDrawMenuBar                 = libuser32.NewProc("DrawMenuBar")
	procDrawTextExW                 = libuser32.NewProc("DrawTextExW")
	procDrawThemeBackground         = libuxtheme.NewProc("DrawThemeBackground")
	procEllipse                     = libgdi32.NewProc("Ellipse")
	procEmptyClipboard              = libuser32.NewProc("EmptyClipboard")
	procEnableWindow                = libuser32.NewProc("EnableWindow")
	procEndDeferWindowPos           = libuser32.NewProc("EndDeferWindowPos")
	procEndPaint                    = libuser32.NewProc("EndPaint")
	procEnumChildWindows            = libuser32.NewProc("EnumChildWindows")
	procExcludeClipRect             = libgdi32.NewProc("ExcludeClipRect")
	procExtCreatePen                = libgdi32.NewProc("ExtCreatePen")
	procFillRgn                     = libgdi32.NewProc("FillRgn")
	procFindResourceW               = libkernel32.NewProc("FindResourceW")
	procFindWindowW                 = libuser32.NewProc("FindWindowW")
	procGdiFlush                    = libgdi32.NewProc("GdiFlush")
	procGdipCreateBitmapFromFile    = libgdiplus.NewProc("GdipCreateBitmapFromFile")
	procGdipCreateHBITMAPFromBitmap = libgdiplus.NewProc("GdipCreateHBITMAPFromBitmap")
	procGdipDisposeImage            = libgdiplus.NewProc("GdipDisposeImage")
	procGetAncestor                 = libuser32.NewProc("GetAncestor")
	procGetCaretPos                 = libuser32.NewProc("GetCaretPos")
	procGetClientRect               = libuser32.NewProc("GetClientRect")
	procGetClipboardData            = libuser32.NewProc("GetClipboardData")
	procGetCurrentThreadId          = libkernel32.NewProc("GetCurrentThreadId")
	procGetCursorPos                = libuser32.NewProc("GetCursorPos")
	procGetDC                       = libuser32.NewProc("GetDC")
	procGetDIBits                   = libgdi32.NewProc("GetDIBits")
	procGetDeviceCaps               = libgdi32.NewProc("GetDeviceCaps")
	procGetDlgItem                  = libuser32.NewProc("GetDlgItem")
	procGetEnhMetaFileW             = libgdi32.NewProc("GetEnhMetaFileW")
	procGetEnhMetaFileHeader        = libgdi32.NewProc("GetEnhMetaFileHeader")
	procGetFocus                    = libuser32.NewProc("GetFocus")
	procGetForegroundWindow         = libuser32.NewProc("GetForegroundWindow")
	procGetIconInfo                 = libuser32.NewProc("GetIconInfo")
	procGetKeyState                 = libuser32.NewProc("GetKeyState")
	procGetLastError                = libkernel32.NewProc("GetLastError")
	procGetLocaleInfoW              = libkernel32.NewProc("GetLocaleInfoW")
	procGetLogicalDriveStringsW     = libkernel32.NewProc("GetLogicalDriveStringsW")
	procGetMenuInfo                 = libuser32.NewProc("GetMenuInfo")
	procGetMessageW                 = libuser32.NewProc("GetMessageW")
	procGetModuleHandleW            = libkernel32.NewProc("GetModuleHandleW")
	procGetMonitorInfoW             = libuser32.NewProc("GetMonitorInfoW")
	procGetObjectW                  = libgdi32.NewProc("GetObjectW")
	procGetOpenFileNameW            = libcomdlg32.NewProc("GetOpenFileNameW")
	procGetParent                   = libuser32.NewProc("GetParent")
	procGetSaveFileNameW            = libcomdlg32.NewProc("GetSaveFileNameW")
	procGetScrollInfo               = libuser32.NewProc("GetScrollInfo")
	procGetSysColor                 = libuser32.NewProc("GetSysColor")
	procGetSysColorBrush            = libuser32.NewProc("GetSysColorBrush")
	procGetTextExtentPoint32W       = libgdi32.NewProc("GetTextExtentPoint32W")
	procGetTextMetricsW             = libgdi32.NewProc("GetTextMetricsW")
	procGetThemeColor               = libuxtheme.NewProc("GetThemeColor")
	procGetVersion                  = libkernel32.NewProc("GetVersion")
	procGetWindow                   = libuser32.NewProc("GetWindow")
	procGetWindowLongW              = libuser32.NewProc("GetWindowLongW")
	procGetWindowPlacement          = libuser32.NewProc("GetWindowPlacement")
	procGetWindowRect               = libuser32.NewProc("GetWindowRect")
	procGlobalAlloc                 = libkernel32.NewProc("GlobalAlloc")
	procGlobalFree                  = libkernel32.NewProc("GlobalFree")
	procGlobalUnlock                = libkernel32.NewProc("GlobalUnlock")
	procGradientFill                = libmsimg32.NewProc("GradientFill")
	procImageList_Add               = libcomctl32.NewProc("ImageList_Add")
	procImageList_AddMasked         = libcomctl32.NewProc("ImageList_AddMasked")
	procImageList_Create            = libcomctl32.NewProc("ImageList_Create")
	procImageList_Destroy           = libcomctl32.NewProc("ImageList_Destroy")
	procImageList_DrawEx            = libcomctl32.NewProc("ImageList_DrawEx")
	procImageList_ReplaceIcon       = libcomctl32.NewProc("ImageList_ReplaceIcon")
	procInitCommonControlsEx        = libcomctl32.NewProc("InitCommonControlsEx")
	procInsertMenuItemW             = libuser32.NewProc("InsertMenuItemW")
	procIntersectClipRect           = libgdi32.NewProc("IntersectClipRect")
	procInvalidateRect              = libuser32.NewProc("InvalidateRect")
	procIsAppThemed                 = libuxtheme.NewProc("IsAppThemed")
	procIsChild                     = libuser32.NewProc("IsChild")
	procIsClipboardFormatAvailable  = libuser32.NewProc("IsClipboardFormatAvailable")
	procIsDialogMessageW            = libuser32.NewProc("IsDialogMessageW")
	procIsWindowEnabled             = libuser32.NewProc("IsWindowEnabled")
	procIsWindowVisible             = libuser32.NewProc("IsWindowVisible")
	procKillTimer                   = libuser32.NewProc("KillTimer")
	procLineTo                      = libgdi32.NewProc("LineTo")
	procLoadCursorW                 = libuser32.NewProc("LoadCursorW")
	procLoadIconW                   = libuser32.NewProc("LoadIconW")
	procLoadImageW                  = libuser32.NewProc("LoadImageW")
	procLoadResource                = libkernel32.NewProc("LoadResource")
	procMessageBoxW                 = libuser32.NewProc("MessageBoxW")
	procMonitorFromWindow           = libuser32.NewProc("MonitorFromWindow")
	procMoveToEx                    = libgdi32.NewProc("MoveToEx")
	procMoveWindow                  = libuser32.NewProc("MoveWindow")
	procMulDiv                      = libkernel32.NewProc("MulDiv")
	procNotifyWinEvent              = libuser32.NewProc("NotifyWinEvent")
	procOleSetContainedObject       = libole32.NewProc("OleSetContainedObject")
	procOleUninitialize             = libole32.NewProc("OleUninitialize")
	procOpenClipboard               = libuser32.NewProc("OpenClipboard")
	procOpenThemeData               = libuxtheme.NewProc("OpenThemeData")
	procPlayEnhMetaFile             = libgdi32.NewProc("PlayEnhMetaFile")
	procPolyline                    = libgdi32.NewProc("Polyline")
	procPostMessageW                = libuser32.NewProc("PostMessageW")
	procPostQuitMessage             = libuser32.NewProc("PostQuitMessage")
	procRegCloseKey                 = libadvapi32.NewProc("RegCloseKey")
	procRegOpenKeyExW               = libadvapi32.NewProc("RegOpenKeyExW")
	procRegQueryValueExW            = libadvapi32.NewProc("RegQueryValueExW")
	procRegisterClassExW            = libuser32.NewProc("RegisterClassExW")
	procRegisterWindowMessageW      = libuser32.NewProc("RegisterWindowMessageW")
	procReleaseCapture              = libuser32.NewProc("ReleaseCapture")
	procReleaseDC                   = libuser32.NewProc("ReleaseDC")
	procRemoveFontMemResourceEx     = libgdi32.NewProc("RemoveFontMemResourceEx")
	procRemoveMenu                  = libuser32.NewProc("RemoveMenu")
	procRoundRect                   = libgdi32.NewProc("RoundRect")
	procSHBrowseForFolderW          = libshell32.NewProc("SHBrowseForFolderW")
	procSHDefExtractIconW           = libshell32.NewProc("SHDefExtractIconW")
	procSHGetFileInfoW              = libshell32.NewProc("SHGetFileInfoW")
	procSHGetPathFromIDListW        = libshell32.NewProc("SHGetPathFromIDListW")
	procSHGetSpecialFolderPathW     = libshell32.NewProc("SHGetSpecialFolderPathW")
	procScreenToClient              = libuser32.NewProc("ScreenToClient")
	procSelectObject                = libgdi32.NewProc("SelectObject")
	procSendMessageW                = libuser32.NewProc("SendMessageW")
	procSetActiveWindow             = libuser32.NewProc("SetActiveWindow")
	procSetBkColor                  = libgdi32.NewProc("SetBkColor")
	procSetBkMode                   = libgdi32.NewProc("SetBkMode")
	procSetBrushOrgEx               = libgdi32.NewProc("SetBrushOrgEx")
	procSetCapture                  = libuser32.NewProc("SetCapture")
	procSetClipboardData            = libuser32.NewProc("SetClipboardData")
	procSetCursor                   = libuser32.NewProc("SetCursor")
	procSetDIBits                   = libgdi32.NewProc("SetDIBits")
	procSetFocus                    = libuser32.NewProc("SetFocus")
	procSetForegroundWindow         = libuser32.NewProc("SetForegroundWindow")
	procSetLastError                = libkernel32.NewProc("SetLastError")
	procSetMenu                     = libuser32.NewProc("SetMenu")
	procSetMenuDefaultItem          = libuser32.NewProc("SetMenuDefaultItem")
	procSetMenuInfo                 = libuser32.NewProc("SetMenuInfo")
	procSetMenuItemInfoW            = libuser32.NewProc("SetMenuItemInfoW")
	procSetParent                   = libuser32.NewProc("SetParent")
	procSetScrollInfo               = libuser32.NewProc("SetScrollInfo")
	procSetStretchBltMode           = libgdi32.NewProc("SetStretchBltMode")
	procSetTextColor                = libgdi32.NewProc("SetTextColor")
	procSetTimer                    = libuser32.NewProc("SetTimer")
	procSetViewportOrgEx            = libgdi32.NewProc("SetViewportOrgEx")
	procSetWindowLongW              = libuser32.NewProc("SetWindowLongW")
	procSetWindowPlacement          = libuser32.NewProc("SetWindowPlacement")
	procSetWindowPos                = libuser32.NewProc("SetWindowPos")
	procSetWindowTheme              = libuxtheme.NewProc("SetWindowTheme")
	procShell_NotifyIconW           = libshell32.NewProc("Shell_NotifyIconW")
	procShowWindow                  = libuser32.NewProc("ShowWindow")
	procSizeofResource              = libkernel32.NewProc("SizeofResource")
	procStretchBlt                  = libgdi32.NewProc("StretchBlt")
	procSysFreeString               = liboleaut32.NewProc("SysFreeString")
	procSystemParametersInfoW       = libuser32.NewProc("SystemParametersInfoW")
	procTrackMouseEvent             = libuser32.NewProc("TrackMouseEvent")
	procTrackPopupMenuEx            = libuser32.NewProc("TrackPopupMenuEx")
	procTranslateMessage            = libuser32.NewProc("TranslateMessage")
	procTransparentBlt              = libmsimg32.NewProc("TransparentBlt")
	procUpdateWindow                = libuser32.NewProc("UpdateWindow")
	procWindowFromDC                = libuser32.NewProc("WindowFromDC")
)

func AddFontMemResourceEx(pFileView uintptr, cjSize uint32, pvResrved unsafe.Pointer, pNumFonts *uint32) HANDLE {
	r1, _, _ := syscall.SyscallN(procAddFontMemResourceEx.Addr(), pFileView, uintptr(cjSize), uintptr(pvResrved), uintptr(unsafe.Pointer(pNumFonts)))
	return HANDLE(r1)
}

func AlphaBlend(hdcDest HDC, xoriginDest int32, yoriginDest int32, wDest int32, hDest int32, hdcSrc HDC, xoriginSrc int32, yoriginSrc int32, wSrc int32, hSrc int32, ftn BLENDFUNCTION) bool {
	r1, _, _ := syscall.SyscallN(procAlphaBlend.Addr(), uintptr(hdcDest), uintptr(xoriginDest), uintptr(yoriginDest), uintptr(wDest), uintptr(hDest), uintptr(hdcSrc), uintptr(xoriginSrc), uintptr(yoriginSrc), uintptr(wSrc), uintptr(hSrc), uintptr(*(*uint32)(unsafe.Pointer(&ftn))))
	return r1 != 0
}

func BeginDeferWindowPos(nNumWindows int32) HDWP {
	r1, _, _ := syscall.SyscallN(procBeginDeferWindowPos.Addr(), uintptr(nNumWindows))
	return HDWP(r1)
}

func BeginPaint(hWnd HWND, lpPaint *PAINTSTRUCT) HDC {
	r1, _, _ := syscall.SyscallN(procBeginPaint.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpPaint)))
	return HDC(r1)
}

func BitBlt(hdc HDC, x int32, y int32, cx int32, cy int32, hdcSrc HDC, x1 int32, y1 int32, rop uint32) bool {
	r1, _, _ := syscall.SyscallN(procBitBlt.Addr(), uintptr(hdc), uintptr(x), uintptr(y), uintptr(cx), uintptr(cy), uintptr(hdcSrc), uintptr(x1), uintptr(y1), uintptr(rop))
	return r1 != 0
}

func CallWindowProc(lpPrevWndFunc uintptr, hWnd HWND, Msg uint32, wParam uintptr, lParam uintptr) uintptr {
	r1, _, _ := syscall.SyscallN(procCallWindowProcW.Addr(), lpPrevWndFunc, uintptr(hWnd), uintptr(Msg), wParam, lParam)
	return r1
}

func ChangeWindowMessageFilterEx(hwnd HWND, message uint32, action uint32, pChangeFilterStruct *CHANGEFILTERSTRUCT) bool {
	r1, _, _ := syscall.SyscallN(procChangeWindowMessageFilterEx.Addr(), uintptr(hwnd), uintptr(message), uintptr(action), uintptr(unsafe.Pointer(pChangeFilterStruct)))
	return r1 != 0
}

func CheckMenuRadioItem(hmenu HMENU, first uint32, last uint32, check uint32, flags uint32) bool {
	r1, _, _ := syscall.SyscallN(procCheckMenuRadioItem.Addr(), uintptr(hmenu), uintptr(first), uintptr(last), uintptr(check), uintptr(flags))
	return r1 != 0
}

func ClientToScreen(hWnd HWND, lpPoint *POINT) bool {
	r1, _, _ := syscall.SyscallN(procClientToScreen.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpPoint)))
	return r1 != 0
}

func CloseClipboard() bool {
	r1, _, _ := syscall.SyscallN(procCloseClipboard.Addr())
	return r1 != 0
}

func CloseEnhMetaFile(hdc HDC) HENHMETAFILE {
	r1, _, _ := syscall.SyscallN(procCloseEnhMetaFile.Addr(), uintptr(hdc))
	return HENHMETAFILE(r1)
}

func CloseThemeData(hTheme HTHEME) HRESULT {
	r1, _, _ := syscall.SyscallN(procCloseThemeData.Addr(), uintptr(hTheme))
	return HRESULT(r1)
}

func CoCreateInstance(rclsid REFCLSID, pUnkOuter *IUnknown, dwClsContext uint32, riid REFIID, ppv *unsafe.Pointer) HRESULT {
	r1, _, _ := syscall.SyscallN(procCoCreateInstance.Addr(), uintptr(unsafe.Pointer(rclsid)), uintptr(unsafe.Pointer(pUnkOuter)), uintptr(dwClsContext), uintptr(unsafe.Pointer(riid)), uintptr(unsafe.Pointer(ppv)))
	return HRESULT(r1)
}

func CoGetClassObject(rclsid REFCLSID, dwClsContext uint32, pvReserved *COSERVERINFO, riid REFIID, ppv *unsafe.Pointer) HRESULT {
	r1, _, _ := syscall.SyscallN(procCoGetClassObject.Addr(), uintptr(unsafe.Pointer(rclsid)), uintptr(dwClsContext), uintptr(unsafe.Pointer(pvReserved)), uintptr(unsafe.Pointer(riid)), uintptr(unsafe.Pointer(ppv)))
	return HRESULT(r1)
}

func CoTaskMemFree(pv uintptr) {
	syscall.SyscallN(procCoTaskMemFree.Addr(), pv)
}

func CombineRgn(hrgnDst HRGN, hrgnSrc1 HRGN, hrgnSrc2 HRGN, iMode int32) int32 {
	r1, _, _ := syscall.SyscallN(procCombineRgn.Addr(), uintptr(hrgnDst), uintptr(hrgnSrc1), uintptr(hrgnSrc2), uintptr(iMode))
	return int32(r1)
}

func CommDlgExtendedError() uint32 {
	r1, _, _ := syscall.SyscallN(procCommDlgExtendedError.Addr())
	return uint32(r1)
}

func CopyEnhMetaFile(hEnh HENHMETAFILE, lpFileName *uint16) HENHMETAFILE {
	r1, _, _ := syscall.SyscallN(procCopyEnhMetaFileW.Addr(), uintptr(hEnh), uintptr(unsafe.Pointer(lpFileName)))
	return HENHMETAFILE(r1)
}

func CreateBitmap(nWidth int32, nHeight int32, nPlanes uint32, nBitCount uint32, lpBits unsafe.Pointer) HBITMAP {
	r1, _, _ := syscall.SyscallN(procCreateBitmap.Addr(), uintptr(nWidth), uintptr(nHeight), uintptr(nPlanes), uintptr(nBitCount), uintptr(lpBits))
	return HBITMAP(r1)
}

func CreateBrushIndirect(plbrush *LOGBRUSH) HBRUSH {
	r1, _, _ := syscall.SyscallN(procCreateBrushIndirect.Addr(), uintptr(unsafe.Pointer(plbrush)))
	return HBRUSH(r1)
}

func CreateCompatibleBitmap(hdc HDC, cx int32, cy int32) HBITMAP {
	r1, _, _ := syscall.SyscallN(procCreateCompatibleBitmap.Addr(), uintptr(hdc), uintptr(cx), uintptr(cy))
	return HBITMAP(r1)
}

func CreateCompatibleDC(hdc HDC) HDC {
	r1, _, _ := syscall.SyscallN(procCreateCompatibleDC.Addr(), uintptr(hdc))
	return HDC(r1)
}

func CreateDIBSection(hdc HDC, pbmi *BITMAPINFOHEADER, usage uint32, ppvBits *unsafe.Pointer, hSection HANDLE, offset uint32) HBITMAP {
	r1, _, _ := syscall.SyscallN(procCreateDIBSection.Addr(), uintptr(hdc), uintptr(unsafe.Pointer(pbmi)), uintptr(usage), uintptr(unsafe.Pointer(ppvBits)), uintptr(hSection), uintptr(offset))
	return HBITMAP(r1)
}

func CreateEnhMetaFile(hdc HDC, lpFilename *uint16, lprc *RECT, lpDesc *uint16) HDC {
	r1, _, _ := syscall.SyscallN(procCreateEnhMetaFileW.Addr(), uintptr(hdc), uintptr(unsafe.Pointer(lpFilename)), uintptr(unsafe.Pointer(lprc)), uintptr(unsafe.Pointer(lpDesc)))
	return HDC(r1)
}

func CreateFontIndirect(lplf *LOGFONT) HFONT {
	r1, _, _ := syscall.SyscallN(procCreateFontIndirectW.Addr(), uintptr(unsafe.Pointer(lplf)))
	return HFONT(r1)
}

func CreateIconIndirect(piconinfo *ICONINFO) HICON {
	r1, _, _ := syscall.SyscallN(procCreateIconIndirect.Addr(), uintptr(unsafe.Pointer(piconinfo)))
	return HICON(r1)
}

func CreateMenu() HMENU {
	r1, _, _ := syscall.SyscallN(procCreateMenu.Addr())
	return HMENU(r1)
}

func CreatePatternBrush(hbm HBITMAP) HBRUSH {
	r1, _, _ := syscall.SyscallN(procCreatePatternBrush.Addr(), uintptr(hbm))
	return HBRUSH(r1)
}

func CreatePopupMenu() HMENU {
	r1, _, _ := syscall.SyscallN(procCreatePopupMenu.Addr())
	return HMENU(r1)
}

func CreateRectRgn(x1 int32, y1 int32, x2 int32, y2 int32) HRGN {
	r1, _, _ := syscall.SyscallN(procCreateRectRgn.Addr(), uintptr(x1), uintptr(y1), uintptr(x2), uintptr(y2))
	return HRGN(r1)
}

func CreateWindowEx(dwExStyle uint32, lpClassName *uint16, lpWindowName *uint16, dwStyle uint32, X int32, Y int32, nWidth int32, nHeight int32, hWndParent HWND, hMenu HMENU, hInstance HINSTANCE, lpParam unsafe.Pointer) HWND {
	r1, _, _ := syscall.SyscallN(procCreateWindowExW.Addr(), uintptr(dwExStyle), uintptr(unsafe.Pointer(lpClassName)), uintptr(unsafe.Pointer(lpWindowName)), uintptr(dwStyle), uintptr(X), uintptr(Y), uintptr(nWidth), uintptr(nHeight), uintptr(hWndParent), uintptr(hMenu), uintptr(hInstance), uintptr(lpParam))
	return HWND(r1)
}

func DefWindowProc(hWnd HWND, Msg uint32, wParam uintptr, lParam uintptr) uintptr {
	r1, _, _ := syscall.SyscallN(procDefWindowProcW.Addr(), uintptr(hWnd), uintptr(Msg), wParam, lParam)
	return r1
}

func DeferWindowPos(hWinPosInfo HDWP, hWnd HWND, hWndInsertAfter HWND, x int32, y int32, cx int32, cy int32, uFlags uint32) HDWP {
	r1, _, _ := syscall.SyscallN(procDeferWindowPos.Addr(), uintptr(hWinPosInfo), uintptr(hWnd), uintptr(hWndInsertAfter), uintptr(x), uintptr(y), uintptr(cx), uintptr(cy), uintptr(uFlags))
	return HDWP(r1)
}

func DeleteDC(hdc HDC) bool {
	r1, _, _ := syscall.SyscallN(procDeleteDC.Addr(), uintptr(hdc))
	return r1 != 0
}

func DeleteEnhMetaFile(hmf HENHMETAFILE) bool {
	r1, _, _ := syscall.SyscallN(procDeleteEnhMetaFile.Addr(), uintptr(hmf))
	return r1 != 0
}

func DeleteObject(ho HGDIOBJ) bool {
	r1, _, _ := syscall.SyscallN(procDeleteObject.Addr(), uintptr(ho))
	return r1 != 0
}

func DestroyIcon(hIcon HICON) bool {
	r1, _, _ := syscall.SyscallN(procDestroyIcon.Addr(), uintptr(hIcon))
	return r1 != 0
}

func DestroyMenu(hMenu HMENU) bool {
	r1, _, _ := syscall.SyscallN(procDestroyMenu.Addr(), uintptr(hMenu))
	return r1 != 0
}

func DestroyWindow(hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procDestroyWindow.Addr(), uintptr(hWnd))
	return r1 != 0
}

func DispatchMessage(lpMsg *MSG) uintptr {
	r1, _, _ := syscall.SyscallN(procDispatchMessageW.Addr(), uintptr(unsafe.Pointer(lpMsg)))
	return r1
}

func DragQueryFile(hDrop HDROP, iFile uint, lpszFile *uint16, cch uint) uint {
	r1, _, _ := syscall.SyscallN(procDragQueryFileW.Addr(), uintptr(hDrop), uintptr(iFile), uintptr(unsafe.Pointer(lpszFile)), uintptr(cch))
	return uint(r1)
}

func DrawIconEx(hdc HDC, xLeft int32, yTop int32, hIcon HICON, cxWidth int32, cyWidth int32, istepIfAniCur uint32, hbrFlickerFreeDraw HBRUSH, diFlags uint32) bool {
	r1, _, _ := syscall.SyscallN(procDrawIconEx.Addr(), uintptr(hdc), uintptr(xLeft), uintptr(yTop), uintptr(hIcon), uintptr(cxWidth), uintptr(cyWidth), uintptr(istepIfAniCur), uintptr(hbrFlickerFreeDraw), uintptr(diFlags))
	return r1 != 0
}

func DrawMenuBar(hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procDrawMenuBar.Addr(), uintptr(hWnd))
	return r1 != 0
}

func DrawTextEx(hdc HDC, lpchText *uint16, cchText int32, lprc *RECT, format uint32, lpdtp *DRAWTEXTPARAMS) int32 {
	r1, _, _ := syscall.SyscallN(procDrawTextExW.Addr(), uintptr(hdc), uintptr(unsafe.Pointer(lpchText)), uintptr(cchText), uintptr(unsafe.Pointer(lprc)), uintptr(format), uintptr(unsafe.Pointer(lpdtp)))
	return int32(r1)
}

func DrawThemeBackground(hTheme HTHEME, hdc HDC, iPartId int32, iStateId int32, pRect *RECT, pClipRect *RECT) HRESULT {
	r1, _, _ := syscall.SyscallN(procDrawThemeBackground.Addr(), uintptr(hTheme), uintptr(hdc), uintptr(iPartId), uintptr(iStateId), uintptr(unsafe.Pointer(pRect)), uintptr(unsafe.Pointer(pClipRect)))
	return HRESULT(r1)
}

func Ellipse(hdc HDC, left int32, top int32, right int32, bottom int32) bool {
	r1, _, _ := syscall.SyscallN(procEllipse.Addr(), uintptr(hdc), uintptr(left), uintptr(top), uintptr(right), uintptr(bottom))
	return r1 != 0
}

func EmptyClipboard() bool {
	r1, _, _ := syscall.SyscallN(procEmptyClipboard.Addr())
	return r1 != 0
}

func EnableWindow(hWnd HWND, bEnable bool) bool {
	r1, _, _ := syscall.SyscallN(procEnableWindow.Addr(), uintptr(hWnd), uintptr(BoolToBOOL(bEnable)))
	return r1 != 0
}

func EndDeferWindowPos(hWinPosInfo HDWP) bool {
	r1, _, _ := syscall.SyscallN(procEndDeferWindowPos.Addr(), uintptr(hWinPosInfo))
	return r1 != 0
}

func EndPaint(hWnd HWND, lpPaint *PAINTSTRUCT) bool {
	r1, _, _ := syscall.SyscallN(procEndPaint.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpPaint)))
	return r1 != 0
}

func EnumChildWindows(hWndParent HWND, lpEnumFunc uintptr, lParam uintptr) bool {
	r1, _, _ := syscall.SyscallN(procEnumChildWindows.Addr(), uintptr(hWndParent), lpEnumFunc, lParam)
	return r1 != 0
}

func ExcludeClipRect(hdc HDC, left int32, top int32, right int32, bottom int32) int32 {
	r1, _, _ := syscall.SyscallN(procExcludeClipRect.Addr(), uintptr(hdc), uintptr(left), uintptr(top), uintptr(right), uintptr(bottom))
	return int32(r1)
}

func ExtCreatePen(iPenStyle uint32, cWidth uint32, plbrush *LOGBRUSH, cStyle uint32, pstyle *uint32) HPEN {
	r1, _, _ := syscall.SyscallN(procExtCreatePen.Addr(), uintptr(iPenStyle), uintptr(cWidth), uintptr(unsafe.Pointer(plbrush)), uintptr(cStyle), uintptr(unsafe.Pointer(pstyle)))
	return HPEN(r1)
}

func FillRgn(hdc HDC, hrgn HRGN, hbr HBRUSH) bool {
	r1, _, _ := syscall.SyscallN(procFillRgn.Addr(), uintptr(hdc), uintptr(hrgn), uintptr(hbr))
	return r1 != 0
}

func FindResource(hModule HMODULE, lpName *uint16, lpType *uint16) HRSRC {
	r1, _, _ := syscall.SyscallN(procFindResourceW.Addr(), uintptr(hModule), uintptr(unsafe.Pointer(lpName)), uintptr(unsafe.Pointer(lpType)))
	return HRSRC(r1)
}

func FindWindow(lpClassName *uint16, lpWindowName *uint16) HWND {
	r1, _, _ := syscall.SyscallN(procFindWindowW.Addr(), uintptr(unsafe.Pointer(lpClassName)), uintptr(unsafe.Pointer(lpWindowName)))
	return HWND(r1)
}

func GdiFlush() bool {
	r1, _, _ := syscall.SyscallN(procGdiFlush.Addr())
	return r1 != 0
}

func GdipCreateBitmapFromFile(filename *uint16, bitmap **GpBitmap) GpStatus {
	r1, _, _ := syscall.SyscallN(procGdipCreateBitmapFromFile.Addr(), uintptr(unsafe.Pointer(filename)), uintptr(unsafe.Pointer(bitmap)))
	return GpStatus(r1)
}

func GdipCreateHBITMAPFromBitmap(bitmap *GpBitmap, hbmReturn *HBITMAP, background ARGB) GpStatus {
	r1, _, _ := syscall.SyscallN(procGdipCreateHBITMAPFromBitmap.Addr(), uintptr(unsafe.Pointer(bitmap)), uintptr(unsafe.Pointer(hbmReturn)), uintptr(background))
	return GpStatus(r1)
}

func GdipDisposeImage(image *GpImage) GpStatus {
	r1, _, _ := syscall.SyscallN(procGdipDisposeImage.Addr(), uintptr(unsafe.Pointer(image)))
	return GpStatus(r1)
}

func GetAncestor(hwnd HWND, gaFlags uint32) HWND {
	r1, _, _ := syscall.SyscallN(procGetAncestor.Addr(), uintptr(hwnd), uintptr(gaFlags))
	return HWND(r1)
}

func GetCaretPos(lpPoint *POINT) bool {
	r1, _, _ := syscall.SyscallN(procGetCaretPos.Addr(), uintptr(unsafe.Pointer(lpPoint)))
	return r1 != 0
}

func GetClientRect(hWnd HWND, lpRect *RECT) bool {
	r1, _, _ := syscall.SyscallN(procGetClientRect.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpRect)))
	return r1 != 0
}

func GetClipboardData(uFormat uint32) HANDLE {
	r1, _, _ := syscall.SyscallN(procGetClipboardData.Addr(), uintptr(uFormat))
	return HANDLE(r1)
}

func GetCurrentThreadId() uint32 {
	r1, _, _ := syscall.SyscallN(procGetCurrentThreadId.Addr())
	return uint32(r1)
}

func GetCursorPos(lpPoint *POINT) bool {
	r1, _, _ := syscall.SyscallN(procGetCursorPos.Addr(), uintptr(unsafe.Pointer(lpPoint)))
	return r1 != 0
}

func GetDC(hWnd HWND) HDC {
	r1, _, _ := syscall.SyscallN(procGetDC.Addr(), uintptr(hWnd))
	return HDC(r1)
}

func GetDIBits(hdc HDC, hbm HBITMAP, start uint32, cLines uint32, lpvBits *byte, lpbmi *BITMAPINFO, usage uint32) int32 {
	r1, _, _ := syscall.SyscallN(procGetDIBits.Addr(), uintptr(hdc), uintptr(hbm), uintptr(start), uintptr(cLines), uintptr(unsafe.Pointer(lpvBits)), uintptr(unsafe.Pointer(lpbmi)), uintptr(usage))
	return int32(r1)
}

func GetDeviceCaps(hdc HDC, index int32) int32 {
	r1, _, _ := syscall.SyscallN(procGetDeviceCaps.Addr(), uintptr(hdc), uintptr(index))
	return int32(r1)
}

func GetDlgItem(hDlg HWND, nIDDlgItem int32) HWND {
	r1, _, _ := syscall.SyscallN(procGetDlgItem.Addr(), uintptr(hDlg), uintptr(nIDDlgItem))
	return HWND(r1)
}

func GetEnhMetaFile(lpName *uint16) HENHMETAFILE {
	r1, _, _ := syscall.SyscallN(procGetEnhMetaFileW.Addr(), uintptr(unsafe.Pointer(lpName)))
	return HENHMETAFILE(r1)
}

func GetEnhMetaFileHeader(hemf HENHMETAFILE, nSize uint32, lpEnhMetaHeader *ENHMETAHEADER) uint32 {
	r1, _, _ := syscall.SyscallN(procGetEnhMetaFileHeader.Addr(), uintptr(hemf), uintptr(nSize), uintptr(unsafe.Pointer(lpEnhMetaHeader)))
	return uint32(r1)
}

func GetFocus() HWND {
	r1, _, _ := syscall.SyscallN(procGetFocus.Addr())
	return HWND(r1)
}

func GetForegroundWindow() HWND {
	r1, _, _ := syscall.SyscallN(procGetForegroundWindow.Addr())
	return HWND(r1)
}

func GetIconInfo(hIcon HICON, piconinfo *ICONINFO) bool {
	r1, _, _ := syscall.SyscallN(procGetIconInfo.Addr(), uintptr(hIcon), uintptr(unsafe.Pointer(piconinfo)))
	return r1 != 0
}

func GetKeyState(nVirtKey int32) int16 {
	r1, _, _ := syscall.SyscallN(procGetKeyState.Addr(), uintptr(nVirtKey))
	return int16(r1)
}

func GetLastError() uint32 {
	r1, _, _ := syscall.SyscallN(procGetLastError.Addr())
	return uint32(r1)
}

func GetLocaleInfo(Locale LCID, LCType LCTYPE, lpLCData *uint16, cchData int32) int32 {
	r1, _, _ := syscall.SyscallN(procGetLocaleInfoW.Addr(), uintptr(Locale), uintptr(LCType), uintptr(unsafe.Pointer(lpLCData)), uintptr(cchData))
	return int32(r1)
}

func GetLogicalDriveStrings(nBufferLength uint32, lpBuffer *uint16) uint32 {
	r1, _, _ := syscall.SyscallN(procGetLogicalDriveStringsW.Addr(), uintptr(nBufferLength), uintptr(unsafe.Pointer(lpBuffer)))
	return uint32(r1)
}

func GetMenuInfo(param0 HMENU, param1 *MENUINFO) bool {
	r1, _, _ := syscall.SyscallN(procGetMenuInfo.Addr(), uintptr(param0), uintptr(unsafe.Pointer(param1)))
	return r1 != 0
}

func GetMessage(lpMsg *MSG, hWnd HWND, wMsgFilterMin uint32, wMsgFilterMax uint32) BOOL {
	r1, _, _ := syscall.SyscallN(procGetMessageW.Addr(), uintptr(unsafe.Pointer(lpMsg)), uintptr(hWnd), uintptr(wMsgFilterMin), uintptr(wMsgFilterMax))
	return BOOL(r1)
}

func GetModuleHandle(lpModuleName *uint16) HINSTANCE {
	r1, _, _ := syscall.SyscallN(procGetModuleHandleW.Addr(), uintptr(unsafe.Pointer(lpModuleName)))
	return HINSTANCE(r1)
}

func GetMonitorInfo(hMonitor HMONITOR, lpmi *MONITORINFO) bool {
	r1, _, _ := syscall.SyscallN(procGetMonitorInfoW.Addr(), uintptr(hMonitor), uintptr(unsafe.Pointer(lpmi)))
	return r1 != 0
}

func GetObject(h HGDIOBJ, c uintptr, pv unsafe.Pointer) int32 {
	r1, _, _ := syscall.SyscallN(procGetObjectW.Addr(), uintptr(h), c, uintptr(pv))
	return int32(r1)
}

func GetOpenFileName(param0 *OPENFILENAME) bool {
	r1, _, _ := syscall.SyscallN(procGetOpenFileNameW.Addr(), uintptr(unsafe.Pointer(param0)))
	return r1 != 0
}

func GetParent(hWnd HWND) HWND {
	r1, _, _ := syscall.SyscallN(procGetParent.Addr(), uintptr(hWnd))
	return HWND(r1)
}

func GetSaveFileName(param0 *OPENFILENAME) bool {
	r1, _, _ := syscall.SyscallN(procGetSaveFileNameW.Addr(), uintptr(unsafe.Pointer(param0)))
	return r1 != 0
}

func GetScrollInfo(hwnd HWND, nBar int32, lpsi *SCROLLINFO) bool {
	r1, _, _ := syscall.SyscallN(procGetScrollInfo.Addr(), uintptr(hwnd), uintptr(nBar), uintptr(unsafe.Pointer(lpsi)))
	return r1 != 0
}

func GetSysColor(nIndex int) uint32 {
	r1, _, _ := syscall.SyscallN(procGetSysColor.Addr(), uintptr(nIndex))
	return uint32(r1)
}

func GetSysColorBrush(nIndex int) HBRUSH {
	r1, _, _ := syscall.SyscallN(procGetSysColorBrush.Addr(), uintptr(nIndex))
	return HBRUSH(r1)
}

func GetTextExtentPoint32(hdc HDC, lpString *uint16, c int32, psizl *SIZE) bool {
	r1, _, _ := syscall.SyscallN(procGetTextExtentPoint32W.Addr(), uintptr(hdc), uintptr(unsafe.Pointer(lpString)), uintptr(c), uintptr(unsafe.Pointer(psizl)))
	return r1 != 0
}

func GetTextMetrics(hdc HDC, lptm *TEXTMETRIC) bool {
	r1, _, _ := syscall.SyscallN(procGetTextMetricsW.Addr(), uintptr(hdc), uintptr(unsafe.Pointer(lptm)))
	return r1 != 0
}

func GetThemeColor(hTheme HTHEME, iPartId int32, iStateId int32, iPropId int32, pColor *COLORREF) HRESULT {
	r1, _, _ := syscall.SyscallN(procGetThemeColor.Addr(), uintptr(hTheme), uintptr(iPartId), uintptr(iStateId), uintptr(iPropId), uintptr(unsafe.Pointer(pColor)))
	return HRESULT(r1)
}

func GetVersion() uint32 {
	r1, _, _ := syscall.SyscallN(procGetVersion.Addr())
	return uint32(r1)
}

func GetWindow(hWnd HWND, uCmd uint32) HWND {
	r1, _, _ := syscall.SyscallN(procGetWindow.Addr(), uintptr(hWnd), uintptr(uCmd))
	return HWND(r1)
}

func GetWindowLong(hWnd HWND, nIndex int32) int32 {
	r1, _, _ := syscall.SyscallN(procGetWindowLongW.Addr(), uintptr(hWnd), uintptr(nIndex))
	return int32(r1)
}

func GetWindowLongPtr(hWnd HWND, nIndex int32) uintptr {
	r1, _, _ := syscall.SyscallN(procGetWindowLongPtr.Addr(), uintptr(hWnd), uintptr(nIndex))
	return r1
}

func GetWindowPlacement(hWnd HWND, lpwndpl *WINDOWPLACEMENT) bool {
	r1, _, _ := syscall.SyscallN(procGetWindowPlacement.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpwndpl)))
	return r1 != 0
}

func GetWindowRect(hWnd HWND, lpRect *RECT) bool {
	r1, _, _ := syscall.SyscallN(procGetWindowRect.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpRect)))
	return r1 != 0
}

func GlobalAlloc(uFlags uint32, dwBytes uintptr) HGLOBAL {
	r1, _, _ := syscall.SyscallN(procGlobalAlloc.Addr(), uintptr(uFlags), dwBytes)
	return HGLOBAL(r1)
}

func GlobalFree(hMem HGLOBAL) HGLOBAL {
	r1, _, _ := syscall.SyscallN(procGlobalFree.Addr(), uintptr(hMem))
	return HGLOBAL(r1)
}

func GlobalUnlock(hMem HGLOBAL) bool {
	r1, _, _ := syscall.SyscallN(procGlobalUnlock.Addr(), uintptr(hMem))
	return r1 != 0
}

func GradientFill(hdc HDC, pVertex *TRIVERTEX, nVertex uint32, pMesh unsafe.Pointer, nMesh uint32, ulMode uint32) bool {
	r1, _, _ := syscall.SyscallN(procGradientFill.Addr(), uintptr(hdc), uintptr(unsafe.Pointer(pVertex)), uintptr(nVertex), uintptr(pMesh), uintptr(nMesh), uintptr(ulMode))
	return r1 != 0
}

func ImageList_Add(himl HIMAGELIST, hbmImage HBITMAP, hbmMask HBITMAP) int32 {
	r1, _, _ := syscall.SyscallN(procImageList_Add.Addr(), uintptr(himl), uintptr(hbmImage), uintptr(hbmMask))
	return int32(r1)
}

func ImageList_AddMasked(himl HIMAGELIST, hbmImage HBITMAP, crMask COLORREF) int32 {
	r1, _, _ := syscall.SyscallN(procImageList_AddMasked.Addr(), uintptr(himl), uintptr(hbmImage), uintptr(crMask))
	return int32(r1)
}

func ImageList_Create(cx int32, cy int32, flags uint32, cInitial int32, cGrow int32) HIMAGELIST {
	r1, _, _ := syscall.SyscallN(procImageList_Create.Addr(), uintptr(cx), uintptr(cy), uintptr(flags), uintptr(cInitial), uintptr(cGrow))
	return HIMAGELIST(r1)
}

func ImageList_Destroy(himl HIMAGELIST) bool {
	r1, _, _ := syscall.SyscallN(procImageList_Destroy.Addr(), uintptr(himl))
	return r1 != 0
}

func ImageList_DrawEx(himl HIMAGELIST, i int32, hdcDst HDC, x int32, y int32, dx int32, dy int32, rgbBk COLORREF, rgbFg COLORREF, fStyle uint32) bool {
	r1, _, _ := syscall.SyscallN(procImageList_DrawEx.Addr(), uintptr(himl), uintptr(i), uintptr(hdcDst), uintptr(x), uintptr(y), uintptr(dx), uintptr(dy), uintptr(rgbBk), uintptr(rgbFg), uintptr(fStyle))
	return r1 != 0
}

func ImageList_ReplaceIcon(himl HIMAGELIST, i int32, hicon HICON) int32 {
	r1, _, _ := syscall.SyscallN(procImageList_ReplaceIcon.Addr(), uintptr(himl), uintptr(i), uintptr(hicon))
	return int32(r1)
}

func InitCommonControlsEx(picce *INITCOMMONCONTROLSEX) bool {
	r1, _, _ := syscall.SyscallN(procInitCommonControlsEx.Addr(), uintptr(unsafe.Pointer(picce)))
	return r1 != 0
}

func InsertMenuItem(hmenu HMENU, item uint32, fByPosition bool, lpmi *MENUITEMINFO) bool {
	r1, _, _ := syscall.SyscallN(procInsertMenuItemW.Addr(), uintptr(hmenu), uintptr(item), uintptr(BoolToBOOL(fByPosition)), uintptr(unsafe.Pointer(lpmi)))
	return r1 != 0
}

func IntersectClipRect(hdc HDC, left int32, top int32, right int32, bottom int32) int32 {
	r1, _, _ := syscall.SyscallN(procIntersectClipRect.Addr(), uintptr(hdc), uintptr(left), uintptr(top), uintptr(right), uintptr(bottom))
	return int32(r1)
}

func InvalidateRect(hWnd HWND, lpRect *RECT, bErase bool) bool {
	r1, _, _ := syscall.SyscallN(procInvalidateRect.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpRect)), uintptr(BoolToBOOL(bErase)))
	return r1 != 0
}

func IsAppThemed() bool {
	r1, _, _ := syscall.SyscallN(procIsAppThemed.Addr())
	return r1 != 0
}

func IsChild(hWndParent HWND, hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procIsChild.Addr(), uintptr(hWndParent), uintptr(hWnd))
	return r1 != 0
}

func IsClipboardFormatAvailable(format uint32) bool {
	r1, _, _ := syscall.SyscallN(procIsClipboardFormatAvailable.Addr(), uintptr(format))
	return r1 != 0
}

func IsDialogMessage(hDlg HWND, lpMsg *MSG) bool {
	r1, _, _ := syscall.SyscallN(procIsDialogMessageW.Addr(), uintptr(hDlg), uintptr(unsafe.Pointer(lpMsg)))
	return r1 != 0
}

func IsWindowEnabled(hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procIsWindowEnabled.Addr(), uintptr(hWnd))
	return r1 != 0
}

func IsWindowVisible(hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procIsWindowVisible.Addr(), uintptr(hWnd))
	return r1 != 0
}

func KillTimer(hWnd HWND, uIDEvent uintptr) bool {
	r1, _, _ := syscall.SyscallN(procKillTimer.Addr(), uintptr(hWnd), uIDEvent)
	return r1 != 0
}

func LineTo(hdc HDC, x int32, y int32) bool {
	r1, _, _ := syscall.SyscallN(procLineTo.Addr(), uintptr(hdc), uintptr(x), uintptr(y))
	return r1 != 0
}

func LoadCursor(hInstance HINSTANCE, lpCursorName *uint16) HCURSOR {
	r1, _, _ := syscall.SyscallN(procLoadCursorW.Addr(), uintptr(hInstance), uintptr(unsafe.Pointer(lpCursorName)))
	return HCURSOR(r1)
}

func LoadIcon(hInstance HINSTANCE, lpIconName *uint16) HICON {
	r1, _, _ := syscall.SyscallN(procLoadIconW.Addr(), uintptr(hInstance), uintptr(unsafe.Pointer(lpIconName)))
	return HICON(r1)
}

func LoadImage(hInst HINSTANCE, name *uint16, type_ uint32, cx int32, cy int32, fuLoad uint32) HANDLE {
	r1, _, _ := syscall.SyscallN(procLoadImageW.Addr(), uintptr(hInst), uintptr(unsafe.Pointer(name)), uintptr(type_), uintptr(cx), uintptr(cy), uintptr(fuLoad))
	return HANDLE(r1)
}

func LoadResource(hModule HMODULE, hResInfo HRSRC) HGLOBAL {
	r1, _, _ := syscall.SyscallN(procLoadResource.Addr(), uintptr(hModule), uintptr(hResInfo))
	return HGLOBAL(r1)
}

func MessageBox(hWnd HWND, lpText *uint16, lpCaption *uint16, uType uint32) int32 {
	r1, _, _ := syscall.SyscallN(procMessageBoxW.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpText)), uintptr(unsafe.Pointer(lpCaption)), uintptr(uType))
	return int32(r1)
}

func MonitorFromWindow(hwnd HWND, dwFlags uint32) HMONITOR {
	r1, _, _ := syscall.SyscallN(procMonitorFromWindow.Addr(), uintptr(hwnd), uintptr(dwFlags))
	return HMONITOR(r1)
}

func MoveToEx(hdc HDC, x int, y int, lppt *POINT) bool {
	r1, _, _ := syscall.SyscallN(procMoveToEx.Addr(), uintptr(hdc), uintptr(x), uintptr(y), uintptr(unsafe.Pointer(lppt)))
	return r1 != 0
}

func MoveWindow(hWnd HWND, X int32, Y int32, nWidth int32, nHeight int32, bRepaint bool) bool {
	r1, _, _ := syscall.SyscallN(procMoveWindow.Addr(), uintptr(hWnd), uintptr(X), uintptr(Y), uintptr(nWidth), uintptr(nHeight), uintptr(BoolToBOOL(bRepaint)))
	return r1 != 0
}

func MulDiv(nNumber int32, nNumerator int32, nDenominator int32) int32 {
	r1, _, _ := syscall.SyscallN(procMulDiv.Addr(), uintptr(nNumber), uintptr(nNumerator), uintptr(nDenominator))
	return int32(r1)
}

func NotifyWinEvent(event uint32, hwnd HWND, idObject int32, idChild int32) {
	syscall.SyscallN(procNotifyWinEvent.Addr(), uintptr(event), uintptr(hwnd), uintptr(idObject), uintptr(idChild))
}

func OleSetContainedObject(pUnknown *IUnknown, fContained bool) HRESULT {
	r1, _, _ := syscall.SyscallN(procOleSetContainedObject.Addr(), uintptr(unsafe.Pointer(pUnknown)), uintptr(BoolToBOOL(fContained)))
	return HRESULT(r1)
}

func OleUninitialize() {
	syscall.SyscallN(procOleUninitialize.Addr())
}

func OpenClipboard(hWndNewOwner HWND) bool {
	r1, _, _ := syscall.SyscallN(procOpenClipboard.Addr(), uintptr(hWndNewOwner))
	return r1 != 0
}

func OpenThemeData(hwnd HWND, pszClassList *uint16) HTHEME {
	r1, _, _ := syscall.SyscallN(procOpenThemeData.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(pszClassList)))
	return HTHEME(r1)
}

func PlayEnhMetaFile(hdc HDC, hmf HENHMETAFILE, lprect *RECT) bool {
	r1, _, _ := syscall.SyscallN(procPlayEnhMetaFile.Addr(), uintptr(hdc), uintptr(hmf), uintptr(unsafe.Pointer(lprect)))
	return r1 != 0
}

func Polyline(hdc HDC, apt unsafe.Pointer, cpt int32) bool {
	r1, _, _ := syscall.SyscallN(procPolyline.Addr(), uintptr(hdc), uintptr(apt), uintptr(cpt))
	return r1 != 0
}

func PostMessage(hWnd HWND, Msg uint32, wParam uintptr, lParam uintptr) uintptr {
	r1, _, _ := syscall.SyscallN(procPostMessageW.Addr(), uintptr(hWnd), uintptr(Msg), wParam, lParam)
	return r1
}

func PostQuitMessage(nExitCode int32) {
	syscall.SyscallN(procPostQuitMessage.Addr(), uintptr(nExitCode))
}

func RegCloseKey(hKey HKEY) int32 {
	r1, _, _ := syscall.SyscallN(procRegCloseKey.Addr(), uintptr(hKey))
	return int32(r1)
}

func RegOpenKeyEx(hKey HKEY, lpSubKey *uint16, ulOptions uint32, samDesired REGSAM, phkResult *HKEY) int32 {
	r1, _, _ := syscall.SyscallN(procRegOpenKeyExW.Addr(), uintptr(hKey), uintptr(unsafe.Pointer(lpSubKey)), uintptr(ulOptions), uintptr(samDesired), uintptr(unsafe.Pointer(phkResult)))
	return int32(r1)
}

func RegQueryValueEx(hKey HKEY, lpValueName *uint16, lpReserved *uint32, lpType *uint32, lpData *byte, lpcbData *uint32) int32 {
	r1, _, _ := syscall.SyscallN(procRegQueryValueExW.Addr(), uintptr(hKey), uintptr(unsafe.Pointer(lpValueName)), uintptr(unsafe.Pointer(lpReserved)), uintptr(unsafe.Pointer(lpType)), uintptr(unsafe.Pointer(lpData)), uintptr(unsafe.Pointer(lpcbData)))
	return int32(r1)
}

func RegisterClassEx(param0 *WNDCLASSEX) ATOM {
	r1, _, _ := syscall.SyscallN(procRegisterClassExW.Addr(), uintptr(unsafe.Pointer(param0)))
	return ATOM(r1)
}

func RegisterWindowMessage(lpString *uint16) uint32 {
	r1, _, _ := syscall.SyscallN(procRegisterWindowMessageW.Addr(), uintptr(unsafe.Pointer(lpString)))
	return uint32(r1)
}

func ReleaseCapture() bool {
	r1, _, _ := syscall.SyscallN(procReleaseCapture.Addr())
	return r1 != 0
}

func ReleaseDC(hWnd HWND, hDC HDC) bool {
	r1, _, _ := syscall.SyscallN(procReleaseDC.Addr(), uintptr(hWnd), uintptr(hDC))
	return r1 != 0
}

func RemoveFontMemResourceEx(h HANDLE) bool {
	r1, _, _ := syscall.SyscallN(procRemoveFontMemResourceEx.Addr(), uintptr(h))
	return r1 != 0
}

func RemoveMenu(hMenu HMENU, uPosition uint32, uFlags uint32) bool {
	r1, _, _ := syscall.SyscallN(procRemoveMenu.Addr(), uintptr(hMenu), uintptr(uPosition), uintptr(uFlags))
	return r1 != 0
}

func RoundRect(hdc HDC, left int32, top int32, right int32, bottom int32, width int32, height int32) bool {
	r1, _, _ := syscall.SyscallN(procRoundRect.Addr(), uintptr(hdc), uintptr(left), uintptr(top), uintptr(right), uintptr(bottom), uintptr(width), uintptr(height))
	return r1 != 0
}

func SHBrowseForFolder(lpbi *BROWSEINFO) uintptr {
	r1, _, _ := syscall.SyscallN(procSHBrowseForFolderW.Addr(), uintptr(unsafe.Pointer(lpbi)))
	return r1
}

func SHDefExtractIcon(pszIconFile *uint16, iIndex int32, uFlags uint32, phiconLarge *HICON, phiconSmall *HICON, nIconSize uint32) HRESULT {
	r1, _, _ := syscall.SyscallN(procSHDefExtractIconW.Addr(), uintptr(unsafe.Pointer(pszIconFile)), uintptr(iIndex), uintptr(uFlags), uintptr(unsafe.Pointer(phiconLarge)), uintptr(unsafe.Pointer(phiconSmall)), uintptr(nIconSize))
	return HRESULT(r1)
}

func SHGetFileInfo(pszPath *uint16, dwFileAttributes uint32, psfi *SHFILEINFO, cbFileInfo uint32, uFlags uint32) uintptr {
	r1, _, _ := syscall.SyscallN(procSHGetFileInfoW.Addr(), uintptr(unsafe.Pointer(pszPath)), uintptr(dwFileAttributes), uintptr(unsafe.Pointer(psfi)), uintptr(cbFileInfo), uintptr(uFlags))
	return r1
}

func SHGetPathFromIDList(pidl uintptr, pszPath *uint16) bool {
	r1, _, _ := syscall.SyscallN(procSHGetPathFromIDListW.Addr(), pidl, uintptr(unsafe.Pointer(pszPath)))
	return r1 != 0
}

func SHGetSpecialFolderPath(hwnd HWND, pszPath *uint16, csidl CSIDL, fCreate bool) bool {
	r1, _, _ := syscall.SyscallN(procSHGetSpecialFolderPathW.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(pszPath)), uintptr(csidl), uintptr(BoolToBOOL(fCreate)))
	return r1 != 0
}

func ScreenToClient(hWnd HWND, lpPoint *POINT) bool {
	r1, _, _ := syscall.SyscallN(procScreenToClient.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpPoint)))
	return r1 != 0
}

func SelectObject(hdc HDC, h HGDIOBJ) HGDIOBJ {
	r1, _, _ := syscall.SyscallN(procSelectObject.Addr(), uintptr(hdc), uintptr(h))
	return HGDIOBJ(r1)
}

func SendMessage(hWnd HWND, Msg uint32, wParam uintptr, lParam uintptr) uintptr {
	r1, _, _ := syscall.SyscallN(procSendMessageW.Addr(), uintptr(hWnd), uintptr(Msg), wParam, lParam)
	return r1
}

func SetActiveWindow(hWnd HWND) HWND {
	r1, _, _ := syscall.SyscallN(procSetActiveWindow.Addr(), uintptr(hWnd))
	return HWND(r1)
}

func SetBkColor(hdc HDC, color COLORREF) COLORREF {
	r1, _, _ := syscall.SyscallN(procSetBkColor.Addr(), uintptr(hdc), uintptr(color))
	return COLORREF(r1)
}

func SetBkMode(hdc HDC, mode int32) int32 {
	r1, _, _ := syscall.SyscallN(procSetBkMode.Addr(), uintptr(hdc), uintptr(mode))
	return int32(r1)
}

func SetBrushOrgEx(hdc HDC, x int32, y int32, lppt *POINT) bool {
	r1, _, _ := syscall.SyscallN(procSetBrushOrgEx.Addr(), uintptr(hdc), uintptr(x), uintptr(y), uintptr(unsafe.Pointer(lppt)))
	return r1 != 0
}

func SetCapture(hWnd HWND) HWND {
	r1, _, _ := syscall.SyscallN(procSetCapture.Addr(), uintptr(hWnd))
	return HWND(r1)
}

func SetClipboardData(uFormat uint32, hMem HANDLE) HANDLE {
	r1, _, _ := syscall.SyscallN(procSetClipboardData.Addr(), uintptr(uFormat), uintptr(hMem))
	return HANDLE(r1)
}

func SetCursor(hCursor HCURSOR) HCURSOR {
	r1, _, _ := syscall.SyscallN(procSetCursor.Addr(), uintptr(hCursor))
	return HCURSOR(r1)
}

func SetDIBits(hdc HDC, hbm HBITMAP, start uint32, cLines uint32, lpBits *byte, lpbmi *BITMAPINFO, ColorUse uint32) int32 {
	r1, _, _ := syscall.SyscallN(procSetDIBits.Addr(), uintptr(hdc), uintptr(hbm), uintptr(start), uintptr(cLines), uintptr(unsafe.Pointer(lpBits)), uintptr(unsafe.Pointer(lpbmi)), uintptr(ColorUse))
	return int32(r1)
}

func SetFocus(hWnd HWND) HWND {
	r1, _, _ := syscall.SyscallN(procSetFocus.Addr(), uintptr(hWnd))
	return HWND(r1)
}

func SetForegroundWindow(hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procSetForegroundWindow.Addr(), uintptr(hWnd))
	return r1 != 0
}

func SetLastError(dwErrCode uint32) {
	syscall.SyscallN(procSetLastError.Addr(), uintptr(dwErrCode))
}

func SetMenu(hWnd HWND, hMenu HMENU) bool {
	r1, _, _ := syscall.SyscallN(procSetMenu.Addr(), uintptr(hWnd), uintptr(hMenu))
	return r1 != 0
}

func SetMenuDefaultItem(hMenu HMENU, uItem uint32, fByPos bool) bool {
	r1, _, _ := syscall.SyscallN(procSetMenuDefaultItem.Addr(), uintptr(hMenu), uintptr(uItem), uintptr(BoolToBOOL(fByPos)))
	return r1 != 0
}

func SetMenuInfo(param0 HMENU, param1 *MENUINFO) bool {
	r1, _, _ := syscall.SyscallN(procSetMenuInfo.Addr(), uintptr(param0), uintptr(unsafe.Pointer(param1)))
	return r1 != 0
}

func SetMenuItemInfo(hmenu HMENU, item uint32, fByPositon bool, lpmii *MENUITEMINFO) bool {
	r1, _, _ := syscall.SyscallN(procSetMenuItemInfoW.Addr(), uintptr(hmenu), uintptr(item), uintptr(BoolToBOOL(fByPositon)), uintptr(unsafe.Pointer(lpmii)))
	return r1 != 0
}

func SetParent(hWndChild HWND, hWndNewParent HWND) HWND {
	r1, _, _ := syscall.SyscallN(procSetParent.Addr(), uintptr(hWndChild), uintptr(hWndNewParent))
	return HWND(r1)
}

func SetScrollInfo(hwnd HWND, nBar int32, lpsi *SCROLLINFO, redraw bool) int32 {
	r1, _, _ := syscall.SyscallN(procSetScrollInfo.Addr(), uintptr(hwnd), uintptr(nBar), uintptr(unsafe.Pointer(lpsi)), uintptr(BoolToBOOL(redraw)))
	return int32(r1)
}

func SetStretchBltMode(hdc HDC, mode int32) int32 {
	r1, _, _ := syscall.SyscallN(procSetStretchBltMode.Addr(), uintptr(hdc), uintptr(mode))
	return int32(r1)
}

func SetTextColor(hdc HDC, color COLORREF) COLORREF {
	r1, _, _ := syscall.SyscallN(procSetTextColor.Addr(), uintptr(hdc), uintptr(color))
	return COLORREF(r1)
}

func SetTimer(hWnd HWND, nIDEvent uintptr, uElapse uint32, lpTimerFunc uintptr) uintptr {
	r1, _, _ := syscall.SyscallN(procSetTimer.Addr(), uintptr(hWnd), nIDEvent, uintptr(uElapse), lpTimerFunc)
	return r1
}

func SetViewportOrgEx(hdc HDC, x int32, y int32, lppt *POINT) COLORREF {
	r1, _, _ := syscall.SyscallN(procSetViewportOrgEx.Addr(), uintptr(hdc), uintptr(x), uintptr(y), uintptr(unsafe.Pointer(lppt)))
	return COLORREF(r1)
}

func SetWindowLong(hWnd HWND, nIndex int32, dwNewLong int32) int32 {
	r1, _, _ := syscall.SyscallN(procSetWindowLongW.Addr(), uintptr(hWnd), uintptr(nIndex), uintptr(dwNewLong))
	return int32(r1)
}

func SetWindowLongPtr(hWnd HWND, nIndex int, dwNewLong uintptr) uintptr {
	r1, _, _ := syscall.SyscallN(procSetWindowLongPtr.Addr(), uintptr(hWnd), uintptr(nIndex), dwNewLong)
	return r1
}

func SetWindowPlacement(hWnd HWND, lpwndpl *WINDOWPLACEMENT) bool {
	r1, _, _ := syscall.SyscallN(procSetWindowPlacement.Addr(), uintptr(hWnd), uintptr(unsafe.Pointer(lpwndpl)))
	return r1 != 0
}

func SetWindowPos(hWnd HWND, hWndInsertAfter HWND, X int32, Y int32, cx int32, cy int32, uFlags uint32) bool {
	r1, _, _ := syscall.SyscallN(procSetWindowPos.Addr(), uintptr(hWnd), uintptr(hWndInsertAfter), uintptr(X), uintptr(Y), uintptr(cx), uintptr(cy), uintptr(uFlags))
	return r1 != 0
}

func SetWindowTheme(hwnd HWND, pszSubAppName *uint16, pszSubIdList *uint16) HRESULT {
	r1, _, _ := syscall.SyscallN(procSetWindowTheme.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(pszSubAppName)), uintptr(unsafe.Pointer(pszSubIdList)))
	return HRESULT(r1)
}

func Shell_NotifyIcon(dwMessage uint32, lpData *NOTIFYICONDATA) bool {
	r1, _, _ := syscall.SyscallN(procShell_NotifyIconW.Addr(), uintptr(dwMessage), uintptr(unsafe.Pointer(lpData)))
	return r1 != 0
}

func ShowWindow(hWnd HWND, nCmdShow int32) bool {
	r1, _, _ := syscall.SyscallN(procShowWindow.Addr(), uintptr(hWnd), uintptr(nCmdShow))
	return r1 != 0
}

func SizeofResource(hModule HMODULE, hResInfo HRSRC) uint32 {
	r1, _, _ := syscall.SyscallN(procSizeofResource.Addr(), uintptr(hModule), uintptr(hResInfo))
	return uint32(r1)
}

func StretchBlt(hdcDest HDC, xDest int32, yDest int32, wDest int32, hDest int32, hdcSrc HDC, xSrc int32, ySrc int32, wSrc int32, hSrc int32, rop uint32) bool {
	r1, _, _ := syscall.SyscallN(procStretchBlt.Addr(), uintptr(hdcDest), uintptr(xDest), uintptr(yDest), uintptr(wDest), uintptr(hDest), uintptr(hdcSrc), uintptr(xSrc), uintptr(ySrc), uintptr(wSrc), uintptr(hSrc), uintptr(rop))
	return r1 != 0
}

func SysFreeString(bstrString *uint16) {
	syscall.SyscallN(procSysFreeString.Addr(), uintptr(unsafe.Pointer(bstrString)))
}

func SystemParametersInfo(uiAction uint32, uiParam uint32, pvParam unsafe.Pointer, fWinIni uint32) bool {
	r1, _, _ := syscall.SyscallN(procSystemParametersInfoW.Addr(), uintptr(uiAction), uintptr(uiParam), uintptr(pvParam), uintptr(fWinIni))
	return r1 != 0
}

func TrackMouseEvent(lpEventTrack *TRACKMOUSEEVENT) bool {
	r1, _, _ := syscall.SyscallN(procTrackMouseEvent.Addr(), uintptr(unsafe.Pointer(lpEventTrack)))
	return r1 != 0
}

func TrackPopupMenuEx(hMenu HMENU, uFlags uint32, x int32, y int32, hwnd HWND, lptpm *TPMPARAMS) BOOL {
	r1, _, _ := syscall.SyscallN(procTrackPopupMenuEx.Addr(), uintptr(hMenu), uintptr(uFlags), uintptr(x), uintptr(y), uintptr(hwnd), uintptr(unsafe.Pointer(lptpm)))
	return BOOL(r1)
}

func TranslateMessage(lpMsg *MSG) bool {
	r1, _, _ := syscall.SyscallN(procTranslateMessage.Addr(), uintptr(unsafe.Pointer(lpMsg)))
	return r1 != 0
}

func TransparentBlt(hdcDest HDC, xoriginDest int32, yoriginDest int32, wDest int32, hDest int32, hdcSrc HDC, xoriginSrc int32, yoriginSrc int32, wSrc int32, hSrc int32, crTransparent uint32) bool {
	r1, _, _ := syscall.SyscallN(procTransparentBlt.Addr(), uintptr(hdcDest), uintptr(xoriginDest), uintptr(yoriginDest), uintptr(wDest), uintptr(hDest), uintptr(hdcSrc), uintptr(xoriginSrc), uintptr(yoriginSrc), uintptr(wSrc), uintptr(hSrc), uintptr(crTransparent))
	return r1 != 0
}

func UpdateWindow(hWnd HWND) bool {
	r1, _, _ := syscall.SyscallN(procUpdateWindow.Addr(), uintptr(hWnd))
	return r1 != 0
}

func WindowFromDC(hDC HDC) HWND {
	r1, _, _ := syscall.SyscallN(procWindowFromDC.Addr(), uintptr(hDC))
	return HWND(r1)
}
